### PR TITLE
Add lock object to protect writes to SQL overwrite caches

### PR DESCRIPTION
**Pull request by safreiberg**
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/649)

### CODE REVIEW

**Comment by clockfort** [comment]
I have no SA on this and probably shouldn't be the primary reviewer unless fry wants to drop some background for it.

**Comment by safreiberg** [comment]
ping

**Comment by jboreiko** [comment]
This needs to be ready for internal release by Friday July 15th.

**Comment by jboreiko** [comment]
I agree with @clockfort, it's a bit odd that we don't actually enforce the safety of the map since it's still accessible from the subclasses.  That said it looks like this fix is already ready to go internally so I will let this in.

**Pull request merged**
