### PR TITLE
Fix StreamingStore cleanup tasks

### PR DESCRIPTION
**Pull request by fsamuel-bs**
**Goals (and why)**: Properly deserialize rows from metadata and index tables on cleanup tasks. This is needed because the row can have two fields when the `.hashFirstRowComponents()` option is used.

The previous code issued deletes to wrong keys, not correctly deleting data.

**Implementation Description (bullets)**: Always `hydrateFromBytes` when deserializing.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2736)

### CODE REVIEW

**Comment by gsheasby** [comment]
That was quick. Can we have a test for this, please?

**Comment by fsamuel-bs** [comment]
@hsaraogi @jeremyk-91 @gsheasby @nziebart for SA.

**Comment by fsamuel-bs** [comment]
Manually testing on internal lightly storage product. We should release as soon as this is merged.

**Comment by fsamuel-bs** [comment]
Tests pass on internal light storage.

**Pull request merged**
