### PR TITLE
Enable baseline for atlasdb-impl-shared

### PR DESCRIPTION
**Pull request by SerialVelocity**
Changes:
  - Mainly cosmetic to match baseline style
  - A few changes are for correctness bugs (supposedly) found by findbugs. 
    - ~~We don't always `synchronise(this)` in `DynamicPartitionMapImpl`. Inside that class, we also don't check `operationsInProgress` in `equals`/`hashCode` anymore.~~ **reverted**
  - A few changes are for efficiency reasons found by findbugs.
    - We were iterating over `keySet`, then using `Map#get`.

Looking through by commit is probably easier.

| Project | Checkstyle main bugs | Checkstyle test bugs |
| --- | --- | --- |
| atlasdb-impl-shared | 1086 | 20 |

**Baseline modifications**
  - Checkstyle
    - Suppress abbreviations in files that have KV in their name (examples: TransactionKVSWrapper, KVTableMappingService)
  - Findbugs suppressions
    - IS_FIELD_NOT_GUARDED for DynamicPartitionMapImpl

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/775)

### CODE REVIEW

**Comment by gsheasby** [comment]
Reviewed 110 of 130 files at r1.
Review status: 110 of 129 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/PartitionedKeyValueService.java, line 108 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSaRWzzmN74xkqDij7:-KPSaRWzzmN74xkqDij8:b-5uu8b7) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/PartitionedKeyValueService.java#L108)):*
> ```Java
> 
>                 // Schedule tasks for execution
>                 input.runForRowsRead(tableRef.getQualifiedName(), rows, kvsAndRowsPair -> {
> ```

BTW - I feel that lambdas can sometimes make things less readable (I have to think more than I like to in order to figure out what's going on here). The comment in the line above is a dead giveaway that a function called `scheduleTasksForExecution` should be extracted.
However, since this is a big fat checkstyle PR, I'm OK with this refactoring not being done here.

There are other such cases in this file. *adds it to the debt tracker*xnnx

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/exception/ClientVersionTooOldException.java, line 70 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPScT__6rnhAWdQS-K9:-KPScT__6rnhAWdQS-KA:bo126zt) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/exception/ClientVersionTooOldException.java#L70)):*
> ```Java
>     public DynamicPartitionMap getUpdatedMap() {
>         return RemotingPartitionMapService.createClientSide(
>                 Preconditions.checkNotNull(pmsUri, "pmsUri must not be nnull to get the updated map")).getMap();
> ```

`nnull`
Also, you should probably spell out the `pms` part of `pmsUri`...

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/DynamicPartitionMapImpl.java, line 280 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSeLWnEyIaJjse2WkJ:-KPSeLWnEyIaJjse2WkK:b2nhipw) ([raw file](https://github.com/palantir/atlasdb/blob/8bc8c61773a273d11965a6ee531d431b436e6458/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/DynamicPartitionMapImpl.java#L280)):*
> ```Java
> 
>     /** Helper methods ***************************************************************************/
>     // This is the METHOD
> ```

LOL

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/InMemoryPartitionMapService.java, line 84 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSeliMw1AOGVMTMFfx:-KPSeliMw1AOGVMTMFfy:b-v5cuqt) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/InMemoryPartitionMapService.java#L84)):*
> ```Java
>         lock.writeLock().lock();
>         try {
>             final long originalVersion = this.partitionMap == null ? -1L : this.partitionMap.getVersion();
> ```

You don't need `this` any more.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/quorum/QuorumTracker.java, line 27 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSfd8agvdVOytPyrCF:-KPSfd8agvdVOytPyrCG:bjo1qm7) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/quorum/QuorumTracker.java#L27)):*
> ```Java
> import com.palantir.common.collect.Maps2;
> 
> public class QuorumTracker<FutureReturnTypeT, TrackingUnitT> {
> ```

Why the random T at the end? Does it stand for "type"? In which case `FutureReturnTypeT` is a tautology.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/server/EndpointServer.java, line 368 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSg4gaPMVPnBgVEgOK:-KPSg4gaPMVPnBgVEgOL:b-f19mg2) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/server/EndpointServer.java#L368)):*
> ```Java
>     public Set<TableReference> getAllTableNames() {
>         return runPartitionMapReadOperation(input -> {
>             // TODO: Hack
> ```

FYI - Looks like another KVS has `HIDDEN_TABLES`...

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/HistoryRangeIterator.java, line 42 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPShmWHipPA7Zc8MSqo:-KPShmWHipPA7Zc8MSqp:b-iy98d7) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/HistoryRangeIterator.java#L42)):*
> ```Java
>     @Override
>     protected ClosableIterator<RowResult<Set<Value>>> getMoreRows(KeyValueService kvs, TableReference tableReference,
>                                                                   RangeRequest newRange, long ts) {
> ```

This is not an improvement.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/RangeIterator.java, line 92 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPShsV8MsXThlw40PG4:-KPShsV8MsXThlw40PG5:b12mya0) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/RangeIterator.java#L92)):*
> ```Java
>             TableReference tableReference,
>             RangeRequest newRange,
>             long ts);
> ```

Again, I prefer `timestamp` to `ts`.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/TimestampsRangeIterator.java, line 42 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSidy-ooAOup8Xg6Kv:-KPSidy-ooAOup8Xg6Kw:bysug0y) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/TimestampsRangeIterator.java#L42)):*
> ```Java
>     protected ClosableIterator<RowResult<Set<Long>>> getMoreRows(KeyValueService kvs, TableReference tableReference,
>                                                                  RangeRequest newRange, long ts) {
>         return kvs.getRangeOfTimestamps(tableReference, newRange, ts);
> ```

Actually, it would be nice to say what this `t(ime)s(tamp)` means. I guess it's the startTimestamp of the current transaction?

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/ValueRangeIterator.java, line 41 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSiz2tkcqlUIaM6fH9:-KPSiz2uDE8czqaqnqQL:bns3e6l) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/ValueRangeIterator.java#L41)):*
> ```Java
>     protected ClosableIterator<RowResult<Value>> getMoreRows(KeyValueService kvs, TableReference tableReference,
>                                                              RangeRequest newRange, long ts) {
>         return kvs.getRange(tableReference, newRange, ts);
> ```

Same comment, different file.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ConservativeSweeper.java, line 50 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmVPDuNOj_xO9BAUk:-KPSmVPDuNOj_xO9BAUl:b5n44wt) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ConservativeSweeper.java#L50)):*
> ```Java
> 
>     @Override
>     public ClosableIterator<RowResult<Value>> getValues(TableReference table, RangeRequest range, long ts) {
> ```

These timestamps could also do with explaining. Are they max? min? sweep? start? immutable? I don't want to read more code to find out!

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/Sweeper.java, line 29 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmhmt6jW2N2-wtIbk:-KPSmhmt6jW2N2-wtIbl:biysnfe) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/Sweeper.java#L29)):*
> ```Java
>     long getSweepTimestamp();
> 
>     ClosableIterator<RowResult<Value>> getValues(TableReference table, RangeRequest range, long ts);
> ```

see ConservativeSweeper

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ThoroughSweeper.java, line 44 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmk_O2CADUys3WJJx:-KPSmk_O2CADUys3WJJy:b-ies92) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ThoroughSweeper.java#L44)):*
> ```Java
> 
>     @Override
>     public ClosableIterator<RowResult<Value>> getValues(TableReference table, RangeRequest range, long ts) {
> ```

See ConservativeSweeper

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/table/common/TableTasks.java, line 54 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSnEFoQChHwL4h2B8e:-KPSnEFoQChHwL4h2B8f:bleqppq) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/table/common/TableTasks.java#L54)):*
> ```Java
> import com.palantir.lock.LockRefreshToken;
> 
> public final class TableTasks {
> ```

BTW - tech debt aplenty in here! So many inner classes...

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java, line 88 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSqui9oqVzLgfeWKXm:-KPSqui9oqVzLgfeWKXn:b-fqwuxe) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java#L88)):*
> ```Java
>  * write/write conflict checking as well as preventing read/write conflicts to attain serializability.
>  */
> public class SerializableTransaction extends SnapshotTransaction {
> ```

There are huge changes to this class, which is also horrible to understand (I just spent 15 minutes reading through it). It looks ok to me, but I'd like someone else to look at this file, so leaving it "unreviewed"

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java, line 458 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSo_ZL32hIFpvQvTPi:-KPSo_ZL32hIFpvQvTPj:b2kyjra) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java#L458)):*
> ```Java
>                 orignalReads = Maps.filterKeys(orignalReads, input -> columns.contains(input.getColumnName()));
> 
>                 if (writesByTable.get(table) != null) {
> ```

BTW - Duplicate code :-( (not blocking as you haven't made it _worse_, but would be happy to see it fixed, now that the duplication is 9 lines long.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java, line 520 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSp2x4cavxE-pZPwmO:-KPSp2x4cavxE-pZPwmP:bv30hlh) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java#L520)):*
> ```Java
> 
>             final ConcurrentNavigableMap<Cell, byte[]> readsForTable = getReadsForTable(table);
>             for (Iterable<Cell> batch : Iterables.partition(cells, 1000)) {
> ```

BTW: nit: magic number

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by gsheasby** [comment]
Reviewed 18 of 130 files at r1.
Review status: 127 of 129 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java, line 979 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSvE8o_fg_oKbRxqIj:-KPSvE8pHfGaIIwxr_sv:b-m7xeqq) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L979)):*
> ```Java
>         }
> 
>         // todo (clockfort) also check if valid table for TTL
> ```

BTW - This reordering looks suspiciously like a behavioural change...

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java, line 1040 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSvMoxYvUN8-T-N-fZ:-KPSvMoxYvUN8-T-N-f_:b-m2gmsv) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L1040)):*
> ```Java
>                 if (newVal >= TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES
>                         && newVal - toAdd < TransactionConstants.WARN_LEVEL_FOR_QUEUED_BYTES) {
>                     log.warn("A single transaction has put quite a few bytes: " + newVal, new RuntimeException(
> ```

BTW - this is sad. I preferred it how it was before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by gsheasby** [comment]
Reviewed 1 of 130 files at r1.
Review status: 128 of 129 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by SerialVelocity** [comment]
Review status: 128 of 129 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/exception/ClientVersionTooOldException.java, line 70 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPScT__6rnhAWdQS-K9:-KPSv-VmrcSE_OEuyxej:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/exception/ClientVersionTooOldException.java#L70)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> `nnull`
> Also, you should probably spell out the `pms` part of `pmsUri`...
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/InMemoryPartitionMapService.java, line 84 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSeliMw1AOGVMTMFfx:-KPSvQ6kxkwuQb_BKS1s:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/map/InMemoryPartitionMapService.java#L84)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> You don't need `this` any more.
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/quorum/QuorumTracker.java, line 27 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSfd8agvdVOytPyrCF:-KPSvdc3yTlsP9vnsxtq:b-nlrjdq) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/partition/quorum/QuorumTracker.java#L27)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Why the random T at the end? Does it stand for "type"? In which case `FutureReturnTypeT` is a tautology.
</details>
Done. Yes, it refers to `Type` I think.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/HistoryRangeIterator.java, line 42 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPShmWHipPA7Zc8MSqo:-KPSx7AXlyfOPLViDvDF:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/HistoryRangeIterator.java#L42)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> This is not an improvement.
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/RangeIterator.java, line 92 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPShsV8MsXThlw40PG4:-KPSxeyNI4AbSbSdBRn3:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/RangeIterator.java#L92)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Again, I prefer `timestamp` to `ts`.
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/TimestampsRangeIterator.java, line 42 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSidy-ooAOup8Xg6Kv:-KPSxfdBDGtKRIjZZwy5:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/TimestampsRangeIterator.java#L42)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Actually, it would be nice to say what this `t(ime)s(tamp)` means. I guess it's the startTimestamp of the current transaction?
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/ValueRangeIterator.java, line 41 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSiz2tkcqlUIaM6fH9:-KPSxg4X1tbrDVo_cT-f:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/remoting/iterators/ValueRangeIterator.java#L41)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Same comment, different file.
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ConservativeSweeper.java, line 50 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmVPDuNOj_xO9BAUk:-KPSxi6sSoXlsuOi1NHg:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ConservativeSweeper.java#L50)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> These timestamps could also do with explaining. Are they max? min? sweep? start? immutable? I don't want to read more code to find out!
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/Sweeper.java, line 29 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmhmt6jW2N2-wtIbk:-KPSxzkQPEQx8znzFV2-:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/Sweeper.java#L29)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> see ConservativeSweeper
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ThoroughSweeper.java, line 44 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSmk_O2CADUys3WJJx:-KPSy-Thdy_jLNQEh9Be:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/sweepers/ThoroughSweeper.java#L44)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> See ConservativeSweeper
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java, line 520 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSp2x4cavxE-pZPwmO:-KPSyTlCN4WJFtZ4M3Dc:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java#L520)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> BTW: nit: magic number
</details>
Done.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java, line 979 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSvE8o_fg_oKbRxqIj:-KPSyzcneEqaqz8t4xaj:b-b1r6vh) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java#L979)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> BTW - This reordering looks suspiciously like a behavioural change...
</details>
It shouldn't be, values.isEmpty() will be true for both values and valuesToWrite or false for both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by gsheasby** [comment]
Reviewed 14 of 17 files at r2.
Review status: 128 of 129 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by gsheasby** [comment]
Review status: 128 of 129 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java, line 88 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/775#-KPSqui9oqVzLgfeWKXm:-KPTDoCdy2bwhBxoRFaj:bs0rmm3) ([raw file](https://github.com/palantir/atlasdb/blob/37ae262dc43526ba1f46744b5f692152dfe92462/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java#L88)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> There are huge changes to this class, which is also horrible to understand (I just spent 15 minutes reading through it). It looks ok to me, but I'd like someone else to look at this file, so leaving it "unreviewed"
</details>
OK, double-checked it myself. LGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Comment by gsheasby** [comment]
Reviewed 1 of 17 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/775)*

**Pull request merged**
