### PR TITLE
add entry to release notes about sweep fixes

### PR DESCRIPTION
**Pull request by rhero**
@jboreiko @gbrova for SA

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/987)

### CODE REVIEW

**Comment by gsheasby** [comment]
So I spoke to @gbrova about this recently. He said (and I agree) that since sweep is experimental, we may continue to find and fix issues, and it might not be necessary to put "fixed a bit of sweep" for each individual issue that we solve. Instead, we'd like to wait until sweep is OK, and then put a release note stating that, and linking to the PRs that solved the various issues.

If any of the sweep issues that we've fixed are known to beta/potential beta customers, though, it might be worthwhile to inform them that we fixed them...

**Comment by rhero** [comment]
What's wrong with calling out all of the individual fixes we have for Sweep? I'd rather call things out when we fix them so we can actually track which version have which fixes. I think the signal that "hey we released this experimental thing, and we're actively fixing issues with it" is a good signal to send.

**Comment by gbrova** [comment]
The same PR also fixes cases where running column-paging sweep on the same table a second time would fail because of the sweep sentinel. 

Consider: "... correctly handles cases where table names have both upper and lowercase characters, _and cases where sweep is run multiple times on the same table._"

**Comment by gbrova** [comment]
Since @rhero is the messaging expert, I'm willing to be overruled :-)   Might still be worth explicitly calling this out as an experimental feature though (e.g. "Column-paging Sweep (currently an experimental feature) correctly handles...")

**Pull request merged**
