### PR TITLE
Upgrade http-remoting 3.41.1 -> 3.43.0 to make tracing delegate nicely

### PR DESCRIPTION
**Pull request by iamdanfox**
**Goals (and why)**:

Pick up a critical http-remoting PR (https://github.com/palantir/http-remoting/pull/799) which ensures that the source of truth of tracing is now the new palantir/tracing-java classes.  

This avoids a nasty situation where downstream consumers of atlasdb could find both `remoting3` and `com.palantir.tracing` classes maintaining their own ThreadLocals and would end up disagreeing about what the current trace is!

**Priority (whenever / two weeks / yesterday)**:

Urgent - this is keeping internal products and http-remoting on RCs!

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3494)

### CODE REVIEW

**Comment by iamdanfox** [comment]
I'm gonna push one more commit to replace your current remoting3 usages with the new com.palantir.tracing classes to avoid the wrapping/unwrapping overhead!

**Comment by iamdanfox** [comment]
Open questions:

- should we `explicitShadow` the new `com.palantir.tracing:*` jars in `atlasdb-cassandra/build.gradle`? [I hope this is not necessary]
- why does atlasdb exclude remoting3's tracing from tritium so much? (These excludes will be redundant as soon as this tritium PR merges: https://github.com/palantir/tritium/pull/100)

**Comment by iamdanfox** [comment]
@tboam @sandorw do you guys want a particular changelog for this (as it shouldn't have any user-facing effects)?

**Comment by iamdanfox** [comment]
@tboam is this good to go now?

**Comment by tboam** [comment]
Yes, merging now.  It got stuck in the Circle outage yesterday but is good to go now.

**Pull request merged**
