### PR TITLE
Require keyspace be specified for cassandra config

### PR DESCRIPTION
**Pull request by pwoody**

### CODE REVIEW

**Comment by clockfort** [comment]
We have to be careful about this sort of change, because it breaks back-compat with existing configurations; more importantly it breaks back compat with the default configs, so it's likely a lot of people will hit it.

@rjullman worth doing this change?
pro: a small bit of extra safety for some customers that are intentionally or unintentionally putting a bunch of disjunct atlas services into the same keyspace (with different timestamp/lock servers... :scream: )
con: break back compat with existing configs and maybe force us to port upgrade tasks or similar to open source atlas in order to upgrade people's settings

**Comment by markelliot** [comment]
fwiw, I'm pretty supportive of this being required vs. implicit, let's just call out the config break in release notes?

**Comment by clockfort** [comment]
I won't stand in the way of progress.

Whoever pulls this back into our ecosystem has to be careful, especially because "atlasdb" is not our default keyspace name in PG.

**Comment by markelliot** [comment]
I don't think PG uses this particular set of configuration, so should be okay?

**Comment by clockfort** [comment]
Ah, yep, forgot we never transitioned to new config format.

**Pull request merged**
