### PR TITLE
upgrade source level to java 8

### PR DESCRIPTION
**Pull request by rjullman**

### CODE REVIEW

**Comment by clockfort** [comment]
think you need to screw with the travis yaml to make it run under java 8

**Comment by clockfort** [comment]
Okay. At least it has actual java8 compat errors now. Do you want to look through them all or me

**Comment by rjullman** [comment]
This slows down the build a little bit, but I think the hit is worth it for upgrading to java 8.  Also I assume travis will upgrade their jdk eventually and we can remove manually upgrade on each build.

**Comment by clockfort** [comment]
lgtm

**Pull request merged**
