### PR TITLE
Use tagged metric registry

### PR DESCRIPTION
**Pull request by fsamuel-bs**
**Goals (and why)**: Applying tagged metrics changes from #2659.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2720)

### CODE REVIEW

**Comment by hsaraogi** [comment]
*[atlasdb-client/src/test/java/com/palantir/atlasdb/util/AtlasDbMetricsTest.java, line 64 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/2720#-KzPnJXY9nz2D4h2IYAr:-KzPnJXY9nz2D4h2IYAs:bazueg) ([raw file](https://github.com/palantir/atlasdb/blob/5828cce3d7009e9d91a9ea1dff4e4485568352e3/atlasdb-client/src/test/java/com/palantir/atlasdb/util/AtlasDbMetricsTest.java#L64)):*
> ```Java
>     @Test(expected = NullPointerException.class)
>     public void nullMetricsCannotBeSet() {
>         AtlasDbMetrics.setMetricRegistries(null, null);
> ```

Add a test where only taggedMetricRegistry is null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2720)*

**Comment by hsaraogi** [comment]
*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java, line 309 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/2720#-KzPndkqGHyrB6ZIg94S:-KzPndkqGHyrB6ZIg94T:bn5b5wz) ([raw file](https://github.com/palantir/atlasdb/blob/5828cce3d7009e9d91a9ea1dff4e4485568352e3/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L309)):*
> ```Java
>         checkInstallConfig(config);
> 
>         AtlasDbMetrics.setMetricRegistries(metricRegistry(), taggedMetricRegistry());
> ```

Thinking further, this behavior is going to be confusing for applications that create multiple TMs, they will end up over-writing the metric registry each time they create a new TM and assume that AtlasDB supports metric registries per TM. We should remove this as this is a dev-break with no real benefits.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2720)*

**Comment by hsaraogi** [comment]
Reviewed 10 of 38 files at r1, 28 of 28 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2720)*

**Comment by gmaretic** [comment]
@fsamuel-bs I am good with merging this in, but I'll let you have another look if you want

**Pull request merged**
