### PR TITLE
Restore Release Notes

### PR DESCRIPTION
**Pull request by rjullman**
Reverts palantir/atlasdb#485

### CODE REVIEW

**Comment by rjullman** [comment]
I think this version of the docs is correct.  The first person to make a 0.6.0 can add the header (or we can add it here).

**Comment by rjullman** [comment]
@gbrova for SA (please correct me if I'm confused about all of this)

**Comment by gbrova** [comment]
I think we might both be confused :P 

If I understand the issue correctly, we're planning to maintain two branches (0.4.x internal LTS, and 0.y.0) and both of the release notes might need to reflect some of the same changes. It's not obvious how to maintain this.  In particular, one problem with the approach here is that if we want to release 0.5.0 right now (before 0.4.1 is released), it's not clear what release the 0.4.1 notes are referring to are someone would have to go in and modify this file. 

I think a better model might be to track only major (0.5.0, 0.6.0, etc) release notes on develop, and update the release notes on the 0.4.x branch separately on that branch. 

Does this make sense? We can also chat in person to iron out details if necessary.

**Comment by clockfort** [comment]
Since the docs website is only served out of the version in develop-branch, and because we thought it would make more sense for someone looking for "what features are in what versions" we wanted to push 0.4.x-related release notes to develop.

I can see your POV though, as well.

**Comment by joelea** [comment]
Goals:

1. Someone can quickly find release notes for recent atlas versions
2. Someone can quickly find release notes for patch releases on old versions
3. We can release (with release notes) by just tagging a version in Github

My proposal to make this work is:

1. Every change that **should be in the release notes** is put there as part of the same merge. 
2. Changes to release notes should be placed in the section for the release where they will appear, which means they should always be put under a release that has not happened yet. This could be a normal release (0.x.0) or a patch release (0.x.y) - the person making the PR will know which is appropriate.
3. If that section doesn't exist, create it. New sections should be added so that versions are ordered lexicographically (*not* temporally)

I think we deleted some and changed some ordering, and you're trying to make it retroactively correct which has caused some weird collisions. I'll put in a commit that *I think* makes everything good for both sides and then we should go with the plan above unless anyone has any issues with it.

**Comment by rjullman** [comment]
I'm still a little confused. Do we put release notes on patch branches? I agree with Chris that it is nice to have all the release notes on the built docs. This can work with Joe's plan given that all patch fixes should probably first be a change on develop. In that system you would add to two places on the release notes simultaneously when making the develop (both to develops future release and the patch branch future release). The only weirdness here is that then you have things twice in the release notes and it is unclear that things in 0.x.y may not appear in 0.x+1.0. The best way I see around this is to have patch releases indicate a backport (as a new heading?) perhaps even indicating the version it came from.

**Comment by joelea** [comment]
Talked in person - we'll cross the 0.x.y bridge when we come to it, but we'll probably just add a "backport" tag alongside "fixed" and "changed" etc.

**Pull request merged**
