### PR TITLE
Backport Log held and outstanding locks in YAML for further processing (#1792)…

### PR DESCRIPTION
**Pull request by cholve**
… (#1824)

Backport from 0.39.3 to 0.4.x
(cherry picked from commit 4299035c358e69b5ccc038debcc0920ba9a59ad9)

**Goals (and why)**:
Would like to have this available for the large internal product, which is currently running on this version of OSS Atlas.

**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:
Ideally by the end of the week.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1913)

### CODE REVIEW

**Comment by cholve** [comment]
@datval Could you review this?  Let me know who else would be good to review.

**Comment by datval** [comment]
Did you cherry-pick? there may be some commits missing then.

**Comment by cholve** [comment]
Yeah cherry-picked this commit 4299035c358e69b5ccc038debcc0920ba9a59ad9, which I thought was a squash of everything that was needed.

**Comment by datval** [comment]
Looks good to me. Can you please also add this: https://github.com/palantir/atlasdb/pull/1882 I think commit is this: be77343
Berler fixed file descriptor leaking.

**Comment by datval** [comment]
Looks good to me. Did you run LockServiceStateLoggerTest? Just resolve conflicts and I think we can merge.

**Comment by datval** [comment]
@cholve  can you please add be77343 into this?

**Comment by cholve** [comment]
@datval Anything else you'd like to see here, or are we good to merge?

**Pull request merged**
