### PR TITLE
use open requests, not borrowed objects, for CassandraClientPool Weig…

### PR DESCRIPTION
**Pull request by jnelson15**
…htedHosts weightings

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/866)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/atlasdb](https://github.com/palantir/atlasdb), @jnelson15! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by jnelson15** [comment]
For context, during a partition, the existing behavior would cause all (most) requests to go to the single partitioned node. This seems to be because calls to borrowObject() can block when creating a socket connection in CassandraClientFactory#create() before actually adding it to allObjects in GenericObjectPool. Therefore, there could be a ton of requests trying to borrow from the same pool even though the "active connection" count could be low.

**Comment by clockfort** [comment]
lgtm. I know you work here, but make the robot believe you and I'll +2

**Comment by jnelson15** [comment]
I signed the CLA thing above. Is there anything else I need to do?

**Comment by clockfort** [comment]
Yep, there we go.

**Pull request merged**
