### PR TITLE
Bump atlasdb-commons and commons-db to Java 8

### LINKED ISSUE #961: Upgrade target compatibility for atlasdb-commons & commons-db to at least Java 1.7
As a developer of AtlasDB, I want to write Java code targeting Java 7 and 8 features, especially on backend modules that require heavy use of exception handling (try-with-resources) and stream operations.

Several AtlasDB modules currently target Java 6 for source & bytecode compatibility. We should be able to bump source & target compatibility for several core backend modules such as `atlasdb-commons`, `commons-db` to at least `1.7` if not `1.8`.

Current Java 6 targeted modules:
```
$ a targetCompatibility | a 1.6
atlasdb-commons/build.gradle:7:targetCompatibility = 1.6
commons-annotations/build.gradle:4:targetCompatibility = 1.6
commons-api/build.gradle:4:targetCompatibility = 1.6
commons-db/build.gradle:4:targetCompatibility = 1.6
commons-executors/build.gradle:7:targetCompatibility = 1.6
commons-proxy/build.gradle:4:targetCompatibility = 1.6
lock-api/build.gradle:7:targetCompatibility = 1.6
```

### PR DESCRIPTION
**Pull request by schlosna**
Upgrade source & target compatibility for several core backend modules atlasdb-commons and commons-db to Java 8.

TODO: release notes & docs

Closes #961

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/962)

### CODE REVIEW

**Comment by gsheasby** [comment]
Do we want to do this yet? Or are we waiting on some unspecified number of "move code from Atlas to the internal product" actions?

**Comment by schlosna** [comment]
@berler & @rjullman for timeframe when this is safe to merge.

**Comment by rjullman** [comment]
I'm not sure if we can upgrade atlasdb-commons due to internal deps, but I imagine commons-db will be fine (since client-side db actions cannot happen in internal code any more).  Regardless, I defer to @berler.

**Comment by berler** [comment]
Bobby is correct. If atlasdb-commons is changed to not use 1.6, we will not be able to upgrade Atlas in internal products (likely not until 1.6 is gone completely from internal).

**Comment by jboreiko** [comment]
Updated change to reflect the comment threads.  Good to merge here.

**Pull request merged**
