### PR TITLE
remove spi project in favor of having the classes in api

### PR DESCRIPTION
**Pull request by jboreiko**
I have two concerns:

- Am I dropping something by removing the dependency on jackson-databind formerly in atlas-spi?
- Should we somehow demarcate the two classes as being used with a ServiceLoader.  Seems a bit strange that only the actual implementations require annotations.  That said I'm not entirely clear on any additional dangers caused by using a ServiceLoader.

### CODE REVIEW

**Comment by clockfort** [comment]
@rjullman to review since I don't know the answer to his questions

**Comment by rjullman** [comment]
- I think jackson-databind is not needed here?
- I'm not sure if there is a standard for marking the classes that are *used* as ServiceLoaders
- I think the separation here between spi and api is good and that in general we shouldn't smash the projects together, but I understand there there are bunch of refactors that are happening and maybe this is a stepping stone to a cleaner world. @joelea

**Comment by joelea** [comment]
@jboreiko this looks good to me - lets merge after fixing the conflicts.

**Comment by jboreiko** [comment]
Does not seem to hold value.  Dropping.

**Pull request closed without merging**
