### PR TITLE
Remove the "elevated" state from the Hikari connection manager

### PR DESCRIPTION
**Pull request by gbonik**
This hack was introduced as a temporary workaround for deadlocking.
Turning up to eleven is fun but doesn't solve the problem.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/971)

### CODE REVIEW

**Comment by schlosna** [comment]
👍 Should we consider completely removing the state machine in there?

**Comment by jboreiko** [comment]
I'm a bit bummed that we can do this removal without modifying a single test.  This is critical path code that has a thread safe state machine inside it (which fortunately just became quite a bit simpler).  I think this would be a good opportunity to add testing for this code.

**Comment by gbonik** [comment]
@jboreiko What exactly would you test here and how? This is just a wrapper around HikariCP (especially after removing the "spinal tap" hack). I could probably simplify the code further (e.g., use Guava's memoizing supplier for lazy initialization -- basically following @schlosna 's suggestion to remove the "state machine")

**Comment by jboreiko** [comment]
Spoke to gbonik offline and decided to add a set of simple tests to check status movements.  Ie after close can I get connections, after startup can I get connections, etc.

**Comment by gsheasby** [comment]
@jboreiko so I understand that it's on @gbonik's plate to add those tests?

**Comment by gbonik** [comment]
@jboreiko I added some tests, let me know if I did something wrong

**Pull request merged**
