### PR TITLE
(please ignore) testing junit parametization / getting CQL tests working on circle CI

### PR DESCRIPTION
**Pull request by clockfort**
making sure some stuff works correctly in Circle CI before I go too far down this rabbit hole.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1301)

### CODE REVIEW

**Comment by clockfort** [comment]
@SerialVelocity (sorry for dragging you into this, and thanks for all of your help)

can you look into why your change to DockerProxySelector breaks the DockerProxySelectorTest#dockerAddressesShouldGoThroughAProxy() ? Looks like it's some weirdness around address name resolution and equality checking

Also, testing locally I still have a weird failure case where after a few hundred tests flow through the socks proxy, it seems to stop working.
It shows up in the tests as CQL complaining about a malformed socks response, and in postgres tests it shows up as a somewhat more specific connection error where it thinks it just receives an EOF.

Other than those things, it looks like I'm good to go and right now I have a few commits on top of this branch just adding tests to the "run with both" category and fixing up ones that are broken

**Comment by SerialVelocity** [comment]
Fixed the tests.

Have you got repro steps for the failure? I can try doing it locally and see what happens.

**Comment by clockfort** [comment]
No specific repro steps :( I just ran all of the tests in the entirety of atlas and eventually they all start failing before finishing the entire test run. Maybe related to amount of data you've transferred over the wire through socks?

**Comment by clockfort** [comment]
Ah, well, it repros on Circle as well. https://circleci.com/gh/palantir/atlasdb/5001

**Comment by clockfort** [comment]
Far more interestingly, I have similar failures now on unrelated branches that have no edits related to any of this: https://circleci.com/gh/palantir/atlasdb/5028
I suspect maybe a bug was introduced in a newer version of the SOCKS proxy docker image we're using, which we would have just started using at any time because we always download the version marked 'latest'.

**Comment by jeremyk-91** [comment]
@clockfort do you still plan to work on this PR?

**Comment by rhero** [comment]
Hey @clockfort - I'm going to close this issue out and leave the branch up. Let me know if you want to fix conflicts and open this back up.

**Pull request closed without merging**
