### PR TITLE
Hooking up serializable transactions again

### PR DESCRIPTION
**Pull request by tmgordeeva**
We've got another potential user of these, so I may as well bring it back and leave it in this time.
This is the same diff as the previous change.

### CODE REVIEW

**Comment by tmgordeeva** [comment]
@jared2501 going to merge this as soon as it passes. I'd actually previously gotten this CR'd and merged, but couldn't use it immediately so I didn't want to leave it in if it wasn't going to be used. Though I probably should've just left it in since it's confusing to have serializability mentioned in docs but be mostly hidden in the code.

**Comment by jared2501** [comment]
thanks @tmgordeeva :) any idea when I can pick this up? (i.e. when the next release will be?)

**Comment by markelliot** [comment]
Hey, reading the change, this is just for the server we ship, and worth noting that the TransactionManagers factory is generally instantiating SerializableTransactionManagers. 

Jared, you're using the client, not the server, so don't think there's impact here?

**Comment by jared2501** [comment]
Ohhh ok got ya - forgot there was a server component to atlas. 

This change also has a change to `TransactionManagers.java` (on line 121) which is on a codepath that I hit using the client, but looking a little closer at it I don't think it impacts us.

**Comment by markelliot** [comment]
Yep, that appears to be just a rename.

**Pull request merged**
