### PR TITLE
Remove jdbckvs

### PR DESCRIPTION
**Pull request by clockfort**
see #1966 , which is also contained here in a lower commit
You can click on the lower commit ( https://github.com/palantir/atlasdb/pull/1967/commits/659f43f2d8ee6a4ad4678348ef4d212e194e5a55 ) to view just the JDBC changes

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1967)

### CODE REVIEW

**Comment by gmaretic** [comment]
@tboam do we have a coherent migration plan?

**Comment by tboam** [comment]
I am not aware of what users of jdbckvs need to do to move off it.  @clockfort is there a migration plan or necessary steps for them to get to DbKVS?

**Comment by tboam** [comment]
From chatting to @jboreiko we can remove Cassandra 1.2 and RocksDB support (see other PRs), but it may not be safe to remove JdbcKVS just yet.

Problems are that DbKVS will silently truncate table names causing potential issues during a migration.  The migration script will detect this case but we need a way to fix these issues if we are requiring people to move them.

Secondly, very wide rows will cause large select statements on the JDBC driver which it can't handle.  In order to migrate these tables we need to change the migration script to batch these selects to the right size.

I'm going to go ahead and send an email announcing Cassandra 1.2 and Rocks removal.  I'll say that JdbcKVS is in the pipeline and people should reach out to us, but I don't think we can push ahead with this work until we have a solution to the issues above.

**Comment by hsaraogi** [comment]
Closing until we have a solution for testing against H2.

**Pull request closed without merging**
