### PR TITLE
Fix/cassandra auth test

### PR DESCRIPTION
**Pull request by gmaretic**
**Goals (and why)**:
Fix the now obsolete failing test breaking develop
**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2297)

### CODE REVIEW

**Comment by tpetracca** [comment]
Why is it obsolete?

**Comment by gmaretic** [comment]
@tpetracca Because we removed authentication from the docker image since we don't really use it and the way it was implemented (with the auth keyspace being on a single node) meant that tests with a degraded cluster could randomly fail. Alternatively, we could have replicated it, but decided to go with the simpler approach unless we change our mind about authentication in production.
Feel free to push back on this if you think it's worth keeping the test, but lets get develop fixed for now.

**Comment by tpetracca** [comment]
Ideally we'd just have a single node that this test ran against. I'm going to be building deployment infrastructure around wiring this all up very soon so it'll start getting usage in the field.

**Comment by gmaretic** [comment]
That's we had we had for this test, but we had interference with the (future) tests for startup independence with a degraded cluster (cannot login to try to create keyspaces). The only fully satisfactory solution then seems to be to recreate the docker image replicating the auth keyspace and then putting back the original test?

**Comment by hsaraogi** [comment]
LGTM.

**Pull request merged**
