### PR TITLE
Revert "Manually run the SafeLogger migration"

### PR DESCRIPTION
**Pull request by j-baker**
Reverts palantir/atlasdb#5572

should not have approved

### CODE REVIEW

**Review by carterkozak — APPROVED** [review]
my approval doesn't do anything here

**Comment by jeremyk-91** [comment]
I'll fix this shortly

**Comment by jeremyk-91** [comment]
👍

**Review by anjor — APPROVED** [review]

**Review by jeremyk-91 — APPROVED** [review]

**Comment by carterkozak** [comment]
@jeremyk-91 are you tracking unreverting this to roll out the SafeLogger migration also?

**Comment by jeremyk-91** [comment]
@carterkozak yes. That'll be in a second PR

**Pull request merged**
