### PR TITLE
Avoid AbstractQueueSynchronizer due to JDK-8191483

### PR DESCRIPTION
**Pull request by AmlingPalantir**
**Goals (and why)**: Work around https://bugs.openjdk.java.net/browse/JDK-8191483

**Implementation Description (bullets)**: 

**Concerns (what feedback would you like?)**: JMM correctness, concurrency bottlenecks, throughput, latency

**Where should we start reviewing?**: JDK bug

**Priority (whenever / two weeks / yesterday)**:

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2712)

### CODE REVIEW

**Comment by jeremyk-91** [comment]
Hmm, this must be in response to the JDK synchronizer bug - looks interesting. I'll wire up our Jepsen lock-correctness tests to this branch some time next week.

Thanks @AmlingPalantir for the PR!

**Comment by schlosna** [comment]
@AmlingPalantir do you more details on the JDK bug ID and repro? Want to really understand the issue and impact as AbstractQueuedSynchronizer has wide ranging implications.

**Comment by jeremyk-91** [comment]
@schlosna I think it's this one: https://bugs.openjdk.java.net/browse/JDK-8191483

**Comment by AmlingPalantir** [comment]
@schlosna: it's the JDK bug linked in one of the commit messages.  I did my best to tell the poor JDK suckers who will have to fix it everything I know about it (and provided a fairly strong repro).  If you want more than that I'm going to need specific questions.

**Comment by schlosna** [comment]
Thanks @jeremyk-91 and @AmlingPalantir , I updated the PR description with that info. Right now it looks like a P3 OpenJDK bug. Martin Bucholz has taken a look and created another repro, so

**Comment by nziebart** [comment]
Ah - looks like it ends up spinning in `tryAcquire`. 

This implementation looks pretty thorough, however I'm hesitant to put such a complex piece of logic into the codebase. Is there a simpler/hackier fix we might be able to do here? Can we just use `tryAcquireNanos` with some really small number in the case where we currently yield and spin?

**Comment by AmlingPalantir** [comment]
I sent the lock service demo (analogous to the one on the JDK bug) to the internal help-atlasdb channel, but I can dig it up again.  Basically a LockServerSync gets corrupted, tryLock() in LockServerLock.*Lock hangs since it can neither tryAcquire[Shared] (barge check refuses) nor figure out who is holding the lock (since no one is).

I had looked briefly at tryAcquireNanos(..., 0) and tryAcquireNanos(..., 1) but 0 will never try to maintain the linked list and even 1 can fail to clean up the linked list if it thinks 1ns has elapsed between the function starting and it reaching the point where it would.

I really don't think trying to paper over one bug in an incredibly complicated parent class with known bugs is a good idea.  While I agree my LockServerSync replacement is on the complex side, it is far easier to get right since it locks the world when it's mucking with the queue (rather than the huge tangle of volatile reads and writes that is AbstractQueuedSynchronizer).

**Comment by AmlingPalantir** [comment]
[1] is my lock server version of the [otherwise] simplest demo.  We have actually seen LockServiceTest.testNumerousClientsPerLock hang and when I ran it in a loop overnight it ended up in a state that looks like the result of that JDK bug (but of course I cannot know precisely that a raced cancel is what happened).

[1] https://gist.github.com/e2dd4fe471d4559f1cee90ae490bce4f

**Comment by nziebart** [comment]
What if we just remove the barging check? This seems to be how `ReentrantLock` avoids the bug.

**Comment by AmlingPalantir** [comment]
Yes, as I already wrote on the JDK bug ReentrantLock.tryLock() calls a nonfair version of tryAcquire() and luckily routes around this bug.

I'll repeat myself:  I really don't think trying to paper over one bug in an incredibly complicated parent class with known bugs is a good idea.

To elaborate:  From the looks of it, AQS is a bug factory and JDK internal use of it only "gets away with it" because it is super duper battle tested.  LockServerSync has no such good fortune.

**Comment by atrocities** [comment]
@jeremyk-91 @nziebart - Ping on this PR? This bug is causing flakes in Gotham testing.

**Comment by nziebart** [comment]
My opinion here is that we should do the simpler fix (remove the no-barging constraint, or use another means of determining if there are queued threads e.g. `getFirstQueuedThread() != null`). It's a large ask for the atlasdb team to review this PR to the extent that we'd feel comfortable merging it and maintaining/supporting it - which we're happy to do if necessary, but the bug here seems to be fixed by the simpler solution.

**Comment by atrocities** [comment]
While I can see that this would be a pretty big ask, I agree with @AmlingPalantir that this is a better solution than stepping around a known bad codepath in a really complicated parent class, which is unlikely to be fixed in the foreseeable future.

In my own opinion, not inheriting from AQS makes this class easier to inspect and reason about. All of the logic is right there. This change consistently passes the tests in atlasdb itself, as well as downstream tests in pgdev (also consistently). 

Happy to talk further about this over VTC or Slack

**Comment by dxiao** [comment]
I made an attempt at documenting the change here: https://github.com/AmlingPalantir/atlasdb/pull/2

**Comment by atrocities** [comment]
After discussing with @nziebart over DM, @sandorw - it sounds like you'll be maintaining this code starting next year. I'd like to talk with you about the relative merits of this solution versus papering over the AQS bug.

Do you have some time next week for a short discussion over vtc, or in person if you're in the shire? Thanks much.

**Comment by atrocities** [comment]
@sandorw seems open to merging in this fix after consulting with some others. Likely candidates are @schlosna and @dxiao .

**Comment by tboam** [comment]
@sandorw to own consulting with others on change and identifying the right path to merging this.

**Comment by schlosna** [comment]
Fixed in future OpenJDK 11: http://hg.openjdk.java.net/jdk/jdk/rev/221cf8307606 & https://bugs.openjdk.java.net/browse/JDK-8191483

**Comment by dxiao** [comment]
*ping* where are we with this?

**Comment by tboam** [comment]
@sandorw are you still open to merging this?  Any concerns?

Sandor is back in on Monday so we'll get an answer then, thanks for the ping.

**Comment by sandorw** [comment]
I'm a bit concerned about the size of this change and how thorough a review + testing it needs. I understand that AQS may have other bugs, but it has significantly more usage than this code has to draw out subtle concurrency issues like the one this PR addresses. I worry that even a thorough review might not catch a similar race in this code that could be hard to detect.

https://github.com/palantir/atlasdb/pull/2799 merged as an alternative in December. It would be nice to confirm that that fix addresses the original issue. To take this change, we want better test coverage and ideally a test that tries to cover the behavior being fixed here. I'm not sure it's worth the extra time investment if #2799 fixes the issue.

**Comment by sandorw** [comment]
Closing this out.

**Pull request closed without merging**
