### PR TITLE
Prepare for baseline!

### PR DESCRIPTION
**Pull request by SerialVelocity**
Changes:
  - Add baseline and configure it with the modifications below (to make it easier to enable on projects for now)
  - The IntelliJ Copyright plugin has been further modified over what baseline does so that it inserts it in our format as a JavaDoc comment.

Looking through by commit is probably easier.

**Extra information**

| Project | Checkstyle main bugs | Checkstyle test bugs |
| --- | --- | --- |
| [atlasdb-impl-shared](https://github.com/palantir/atlasdb/pull/775) | 1086 | 20 |
| [atlasdb-dropwizard-bundle](https://github.com/palantir/atlasdb/pull/776) | 6 | 0 |
| [atlasdb-dbkvs](https://github.com/palantir/atlasdb/pull/777) | 516 | 8 |
| [atlasdb-api](https://github.com/palantir/atlasdb/pull/778) | 209 | 2 |
| [atlasdb-hikari](https://github.com/palantir/atlasdb/pull/779) | 0 | 0 |
| [atlasdb-cassandra](https://github.com/palantir/atlasdb/pull/780) | 843 | 0 |

**Baseline modifications**
  - Checkstyle:
    - /Checker/RegexpHeader/header
    - /Checker/ImportOrder/groups
    - /Checker/VisibilityModifier
    - /Checker/CyclomaticComplexity
  - Copyright (apache 2.0 -> BSD 3)
  - Eclipse static prefs
    - org.eclipse.jdt.ui.importorder
  - Idea palantir style
    - IMPORT_LAYOUT_TABLE
  - Findbugs suppressions
    - /META-INF/
    - EI_EXPOSE_REP2
    - PT_EXTENDS_CONCRETE_TYPE
    - PT_FINAL_TYPE_CONSTRUCTOR
    - PT_FINAL_TYPE_PARAM
    - PT_FINAL_TYPE_RETURN

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/772)

### CODE REVIEW

**Comment by jboreiko** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.baseline/checkstyle/checkstyle-suppressions.xml, line 21 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0BIlU3tWXwL9Bc-s:-KPF0BImR-xsI35MAhii:b-mp4tks) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle-suppressions.xml#L21)):*
> ```XML
>     <suppress files="\.(bdr|eot|gif|gzip|jar|json|otf|png|svg|ttf|woff|zip)$" checks="NewlineAtEndOfFile" />
> 
>     
> ```

What is the justification for this?  Seems that since we expect this to be the code used by our consumers that we would want it to be easily consumable / readable

---

*[.baseline/checkstyle/checkstyle.xml, line 341 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0s9UgJWjt8IZGDIL:-KPF0s9UgJWjt8IZGDIM:b80sim7) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle.xml#L341)):*
> ```XML
>         </module>
>         <module name="UpperEll"/> 
>          
> ```

nit: why comment these out when we have the file for suppressing, makes it clearer what has been disabled.

---

*[.baseline/eclipse/dynamic/dotfile.checkstyle, line 1 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF2UlqQwzIOYqorpjX:-KPF2UlqQwzIOYqorpjY:btcc0ao) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/eclipse/dynamic/dotfile.checkstyle#L1)):*
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> ```

What is this file?

---

*[.baseline/findbugs/excludeFilter.xml, line 16 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF3tEzPQLQNHNdZjo5:-KPF3tEzPQLQNHNdZjo6:blih99e) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/findbugs/excludeFilter.xml#L16)):*
> ```XML
>     <Match>
>         <Or>
>             <Source name="~.*/META-INF/.*" />
> ```

can we get comments similar to below that justify the removal of these.

---

*[gradle/shared.gradle, line 32 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF4A-0Qm3d_CY1ZqJd:-KPF4A-0Qm3d_CY1ZqJe:b-jewpzm) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/gradle/shared.gradle#L32)):*
> ```Gradle
> 
> dependencies {
>     checkstyle 'com.puppycrawl.tools:checkstyle:6.18'
> ```

since we have it in two places can we toss it in the versions file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/772)*

**Comment by SerialVelocity** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.baseline/checkstyle/checkstyle-suppressions.xml, line 21 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0BIlU3tWXwL9Bc-s:-KPFldkjm4UHUH_J_P1W:b-e8bpk5) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle-suppressions.xml#L21)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> What is the justification for this?  Seems that since we expect this to be the code used by our consumers that we would want it to be easily consumable / readable
</details>
This is generated baseline but I think I agree with it. The code that goes into these folders is generated by things like Immutables, AutoValue, etc. This isn't AtlasDB generated code. The files in this folder shouldn't even be committed.

---

*[.baseline/checkstyle/checkstyle.xml, line 341 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0s9UgJWjt8IZGDIL:-KPFm4irokAivF_2GhNO:b-1q9obd) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle.xml#L341)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> nit: why comment these out when we have the file for suppressing, makes it clearer what has been disabled.
</details>
These are baseline disabled things. All of our disabled things are listed in the table in the PR notes. I'm hoping to get us to vanilla baseline after a while.

---

*[.baseline/eclipse/dynamic/dotfile.checkstyle, line 1 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF2UlqQwzIOYqorpjX:-KPFmICkFYJxMSZRirwE:b-vzoqa5) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/eclipse/dynamic/dotfile.checkstyle#L1)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> What is this file?
</details>
Probably a file to say where checkstyle is configured for eclipse users.

---

*[.baseline/findbugs/excludeFilter.xml, line 16 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF3tEzPQLQNHNdZjo5:-KPFmTjGC3RzPUp6ebLG:b-eba9g2) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/findbugs/excludeFilter.xml#L16)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> can we get comments similar to below that justify the removal of these.
</details>
Sure, how does `<!-- Too time consuming to enable these for now -->` sound?

---

*[gradle/shared.gradle, line 32 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF4A-0Qm3d_CY1ZqJd:-KPFn6nA72vyHuhIjWq-:b-lof2zx) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/gradle/shared.gradle#L32)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> since we have it in two places can we toss it in the versions file.
</details>
Will do. Hopefully, once everything is converted over to baseline, we can remove all of the checkstyle stuff in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/772)*

**Comment by jboreiko** [comment]
Review status: 13 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[.baseline/checkstyle/checkstyle-suppressions.xml, line 21 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0BIlU3tWXwL9Bc-s:-KPJkdfPH5gThVAgcHvl:btvdon5) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle-suppressions.xml#L21)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> This is generated baseline but I think I agree with it. The code that goes into these folders is generated by things like Immutables, AutoValue, etc. This isn't AtlasDB generated code. The files in this folder shouldn't even be committed.
</details>
Ah good point

---

*[.baseline/checkstyle/checkstyle.xml, line 341 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/772#-KPF0s9UgJWjt8IZGDIL:-KPJkmdfiYF2wQ8C0ysS:bsrfk3e) ([raw file](https://github.com/palantir/atlasdb/blob/fd0385a9727948ffe22cdca9351b48d68f50be80/.baseline/checkstyle/checkstyle.xml#L341)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> These are baseline disabled things. All of our disabled things are listed in the table in the PR notes. I'm hoping to get us to vanilla baseline after a while.
</details>
Right, but isn't the visibility modifier one of the listed things?  I just want to make it easy for people to know why we aren't running something.  I don't see them going to check this PR for the things we opted out of

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/772)*

**Comment by jboreiko** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/772#-:-KPJlKaA9ZLisQH7oMlS:bnfp4nl)*

**Pull request merged**
