### PR TITLE
adjust lock test waiting to avoid timeouts

### PR DESCRIPTION
**Pull request by rjullman**

### CODE REVIEW

**Comment by rjullman** [comment]
internal infrastructure is having rare timeouts -- I think increasing the limits here should be enough to fix it.

**Comment by joelea** [comment]
I think we need to go through and add proper time controlled unit tests to this stuff, but this looks fine to make the build flakes go away right now.

**Comment by jboreiko** [comment]
@rjullman do we have pre-merge runs internally to check whether this is helpful before merging into develop?

**Comment by rjullman** [comment]
Not really.  The only real way to test this is to have it running for a long time.  The flickers are already incredibly rare.  The issue here is that in the bowels of this code there is a bunch of threaded "eventually" guarantees.  Normally "eventually" here means within 10 millis, but no one promises that.

**Pull request merged**
