### PR TITLE
configurable lock server options

### PR DESCRIPTION
**Pull request by nziebart**
Allow user to configure lock server options.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/967)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/atlasdb](https://github.com/palantir/atlasdb), @nziebart! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by jboreiko** [comment]
hey @nziebart I am interested in what lock config parameters you are interested in accessing / modifying?  Happy to take internal if required.  Cheers!

**Comment by nziebart** [comment]
@jboreiko We are currently using the lock service for distributed locking. the main thing we'd like to adjust is the maximum blocking time in `LockRequest`. Currently, it's a max of 60 seconds, or indefinite  - 60 seconds being a bit too short, and indefinite being undesirable for multiple reasons.

**Comment by jboreiko** [comment]
Moving to #984 where we all have write perms.  @nziebart let me know if you need write on the repo, you should be fine if you have signed up to be a part of the palantir org.

**Pull request closed without merging**
