### PR TITLE
Add/publish protos used internally

### PR DESCRIPTION
**Pull request by jboreiko**
Our large internal product contains a slightly different version of the time and lock services that uses protobuffers for its wire format.  We could implement a system for having these import the ones we use here but instead have chosen to keep them all in one place and publish the build classes as part of our api.  These were removed as part of #1384 .  Here I have added them back and generated the necessary classes for export as part of their respective libs.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1489)

### CODE REVIEW

**Comment by rhero** [comment]
We expect this to provide perf benefits, right? We should probably document the before and after when we do our scale testing this week.

**Comment by jboreiko** [comment]
So this is a bit different and has a lot more to do with where protobufs are actually rendered into java classes and less to do with changing over the impl to the perf-ier one.  I'm happy to discuss the particulars in person but the gist is it simplifies the other teams build structures to have this stuff generated and published here.

**Comment by rhero** [comment]
@jboreiko did you want this looked at? Who would be good to have review this?

**Comment by jboreiko** [comment]
Really anyone, they just need to take a moment to ensure that the protos get regenerated properly and that it is in fact a revert of the prior change.  I had originally tagged bullman because he is aware of the additional context here (ie, that these are used by an internal product that doesn't want to have an overly complex proto dependency structure).

**Comment by gsheasby** [comment]
They are indeed the same - right down to the inconsistent newline-at-end-of-files. However, the previous change included some build.gradle stuff too - do we want to undo that (i.e. remove the protobuf/sourceSets blocks) too?

Other than that, it would be nice to somehow exclude these files from code coverage statistics.

**Pull request merged**
