### PR TITLE
Log getFreshTimestamp failure at warn

### PR DESCRIPTION
**Pull request by datval**
Backport of #720 to 0.4.x branch

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1628)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/atlasdb](https://github.com/palantir/atlasdb), @datval! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by gsheasby** [comment]
LGTM but you need to update your forked branch by pulling in 0.4.x.

**Comment by datval** [comment]
@gsheasby do you have flickery tests? Is there any way to get more detailed logs?

**Comment by gsheasby** [comment]
Looks like these tests are flickering, but I can't rebuild your branch to check.

**Comment by datval** [comment]
Now it just times out: https://circleci.com/gh/datval/atlasdb/5

**Comment by gsheasby** [comment]
Unfortunately that can happen, especially on old branches :( We might have more success if the branch was unforked (at least then I can keep rebuilding until it passes...).

It's so small a change that I'll just do this, maybe I'll be luckier.

**Comment by gsheasby** [comment]
Merged as #1688.

**Pull request closed without merging**
