### PR TITLE
Expand testing of TM.create methods

### PR DESCRIPTION
**Pull request by gsheasby**
All TransactionManagers.create methods should now be tested.
[no release notes]

**Goals (and why)**: Extra testing of TM.create methods after catching #2581 - see [this comment](https://github.com/palantir/atlasdb/pull/2582#pullrequestreview-72551750).

**Implementation Description (bullets)**: Tested each method, using code coverage as a guide.

**Priority (whenever / two weeks / yesterday)**: whenever

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2595)

### CODE REVIEW

**Comment by hsaraogi** [comment]
How did this change pass the tests after the `namespace` change? See #2601.

**Comment by hsaraogi** [comment]
Ohh, answered my question. The reason is we dint regenerate the generated schemas.

**Comment by gsheasby** [comment]
Yep, my bad. We should consider a `verifyGeneratedSchemasAreCurrent` check to go alongside the one for dependency locks. Could be a *small task* (I'll add it to my personal queue)

**Comment by gsheasby** [comment]
Not that small. I pushed up my work so far here: [gsheasby/infra/verify-generated-schemas](https://github.com/palantir/atlasdb/tree/gsheasby/infra/verify-generated-schemas) - but won't be pursuing further at this time due to other priorities.

**Pull request merged**
