### PR TITLE
Leader election loggin 0.39.x

### PR DESCRIPTION
**Pull request by datval**
**Goals (and why)**:
Cherry-pick changes made on develop for lock leadership election logging.
Customer is still on 0.39 and not sure if there is a plan to upgrade.

**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:
this week

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3296)

### CODE REVIEW

**Comment by jeremyk-91** [comment]
I'm closing and reopening to see if this triggers a build - not sure why this isn't building

**Comment by datval** [comment]
@jeremyk-91 Do we even have SafeArg in 0.39?

**Comment by jeremyk-91** [comment]
Good point - we don't, 0.39.x predates the loggingargs stuff

**Comment by jeremyk-91** [comment]
All good!

**Pull request merged**
