### PR TITLE
Lock server logging now can log refreshing thread

### PR DESCRIPTION
**Pull request by datval**
**Goals (and why)**:
Lock service state logging was very useful. Top requested feature was to include lock refreshing thread.

**Implementation Description (bullets)**:

- Add refreshingThread to LockRefreshToken. Client can set it.
- During refreshing lock, refreshingThread will be transferred to HeldLocksToken and logged when requested.
- This should be used only during refresh, so during other times it will be just null.

**Concerns (what feedback would you like?)**:

- General review
- Is it safe to change?
- Is it OK to be Nullable?

**Where should we start reviewing?**:

From LockServiceImpl

**Priority (whenever / two weeks / yesterday)**:

This week

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2422)

### CODE REVIEW

**Comment by berler** [comment]
Are we sure that the refreshing thread is consistent? There could be (and there definitely has been in the past) product bugs that caused locks to be refreshed by multiple distinct threads.  I think it would make more sense for the metadata of the refreshing thread to be attached to only the API call in which the refresh is requested, and have the server (optionally) save that metadata internally.  It does not make sense to save another string on the HeldLocksToken.

**Comment by datval** [comment]
This will log the latest refreshing thread. It is much better than what we have right now. This is already attached to the API call as LockRefreshToken contains it.
HeldLockToken already has creatingThread, why not refreshingThread? I agree HeldLockToken is overused and likely should be another metadata store, but not sure if it worth to add for this.

If we add the store, we can track all refreshing threads and log the whole history of refreshers.

**Comment by gsheasby** [comment]
(pinging a stale PR) Do we still want to add this (or something like this)? @jeremyk-91 @datval

**Comment by tboam** [comment]
@datval do you still believe this is valuable?

**Comment by datval** [comment]
After some internal feedback, I believe this is not valuable anymore. We decided not to go this way.

**Pull request closed without merging**
