### PR TITLE
Make timeout 5 minutes

### LINKED ISSUE #1288: Shorter timeouts (optimising time to failed build)
"12 fun ways to speed up your circle builds", # 12

We may have already done this. I remember some builds waiting for 10 minutes before giving up.

Internal product comment: "Previously we were waiting 20 minutes after no console output before failing a build.  This used up circle resources and seemed unnecessary.  We make sure that working tests log frequently and have dropped this to 5 minutes.  (Docker pull is usually the worst offender here)."

### PR DESCRIPTION
**Pull request by hsaraogi**
Fix #1288.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1308)

### CODE REVIEW

**Comment by SerialVelocity** [comment]
We can probably set this to 2 minutes since our longest test usually takes 60 seconds according to circle.

**Comment by hsaraogi** [comment]
Making it 150s to be safe. (2.5 minutes)

**Comment by harrybiddle** [comment]
I suggest that we ping off rebuild on this PR a bunch of times to see if there's any effect, out of working hours. (Grgur did this on his PR and saw a 5/9 success rate....!)

**Comment by hsaraogi** [comment]
@harrybiddle : I did this on the 2.5 minute timeout, realized some docker images take upto 3:15 to download and this may timeout for them. I guess 5 minutes will be happy. Still will kick off 3 builds at lunch to confirm.

**Pull request merged**
