### PR TITLE
use immutables

### PR DESCRIPTION
**Pull request by pnepywoda**
having config objects be .equals() to each other means we can do auto-reloading from the filesystem and compare to what it was previously (and only take action if something changed)

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1587)

### CODE REVIEW

**Comment by pnepywoda** [comment]
I can't see what I need to do to bypass the changelog failure (this requires no changelog modifications)

**Comment by pnepywoda** [comment]
@clockfort ping. dunno what the circleci-internal failure is :(

**Comment by jeremyk-91** [comment]
This broke a bunch of tests on other internal products that depended on this.

I'm going to revert to final class, but have the config objects be equals() to each other.

@pnepywoda @clockfort for SA

**Comment by pnepywoda** [comment]
I guess other products are making InMemoryAtlasDbConfig in java code and not using jackson? Kinda weird....but ok. thanks

**Comment by jeremyk-91** [comment]
Yep, other products were directly instantiating InMemoryAtlasDbConfig. Sorry for the inconvenience

**Comment by jboreiko** [comment]
revert can be found here https://github.com/palantir/atlasdb/pull/1627

**Pull request merged**
