### PR TITLE
Fix typo in CQLSH instructions

### PR DESCRIPTION
**Pull request by szunami**
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3598)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/atlasdb](https://github.com/palantir/atlasdb), @szunami! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by szunami** [comment]
I've signed the CLA, not sure why the check isn't complete @tpetracca

**Comment by sandorw** [comment]
CI hasn't run since the change is from a fork. You can push the same change again, not from a fork, and include the message [no release notes] in your commit message to skip the changelog check. Then we should be good to go.

**Comment by gmaretic** [comment]
Reopened as https://github.com/palantir/atlasdb/pull/3636

**Pull request closed without merging**
