### PR TITLE
be smarter about column selection for all columns in fixed column tab…

### LINKED ISSUE #678: CassandraKVS#getRowsForSingleHost() appears to unnecessarily load full cell history
`CassandraKVS#getRowsForSingleHost()` builds a `SliceRange` which includes all Cassandra row columns (resulting in the loading of the full history of the row).  It then discards all values when the exception of the max value less than the passed in `startTs`.  

This is particularly odd considering that if you instead only load a subset of the columns the `Cassandra#getRows()` method instead delegates to `Cassandra#getRowsForSpecificColumns()` which by passes the full loading of the history by instead using a call to `loadWithTs()` with `loadAllTs` set to false.

Again tagging in @clockfort / @tmgordeeva for some historical context

### PR DESCRIPTION
**Pull request by tpetracca**
…les; resolves #678 

CC @tmgordeeva @clockfort 

It's worth noting that the only real code change here is in the TableRenderer class.  The rest is just generated code that changed as a result.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/713)

### CODE REVIEW

**Comment by schlosna** [comment]
Need to make sure we put something in release notes so folks regenerate their schemas' code

**Comment by hsaraogi** [comment]
:lgtm:

---

Reviewed 1 of 18 files at r1.
Review status: 1 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713#-:-KNT7kk5p1AijMftFnuy:1417088721)*

**Comment by clockfort** [comment]
I submitted the same change on our internal stuff a year ago; twilson wouldn't let me merge it without comparitive perf testing, which no one ever got around to.

**Comment by j-baker** [comment]
This allows optimisations like https://github.com/palantir/atlasdb/pull/690 to be much more generally useful - e.g. turning index scans into index lookups.

**Comment by joelea** [comment]
@tpetracca can you add release notes and we'll merge this.

**Comment by jboreiko** [comment]
Reviewed 18 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java, line 223 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/713#-KOI9hkgHP6IbGNw4Al3:-KOI9hkhZHw8wL_L2g8R:1636262375) ([raw file](https://github.com/palantir/atlasdb/blob/59a26b6c6d4f10266beb3c5bb539ff5d1279ec20/atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java#L223)):*
> ```Java
>         @Override
>         public int hashCode() {
>             return Arrays.deepHashCode(new Object[]{ firstComponentHash, id });
> ```

Interesting that this missed the last schema update.  We need to add schema generation to our build process.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713)*

**Comment by jboreiko** [comment]
@rjullman is there any reason we couldn't add a micro bench mark for this case?  A more general question being is it ready for us to start writing tests?

**Comment by schlosna** [comment]
:lgtm:

---

Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713#-:-KOfSMA1TJyjIwiNGUsU:bnfp4nl)*

**Comment by schlosna** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java, line 223 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/713#-KOI9hkgHP6IbGNw4Al3:-KOfVmX4OOgSByCFSsxB:b-s0692c) ([raw file](https://github.com/palantir/atlasdb/blob/59a26b6c6d4f10266beb3c5bb539ff5d1279ec20/atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java#L223)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Interesting that this missed the last schema update.  We need to add schema generation to our build process.
</details>
agreed that seems like it wasn't generated properly before, likely due to #703 . Shouldn't block merging this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713)*

**Comment by tpetracca** [comment]
Review status: 18 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java, line 223 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/713#-KOI9hkgHP6IbGNw4Al3:-KOfX3B6QwUI-pdWtOGY:bc893h6) ([raw file](https://github.com/palantir/atlasdb/blob/59a26b6c6d4f10266beb3c5bb539ff5d1279ec20/atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamIdxTable.java#L223)):*
<details><summary><i>Previously, schlosna (David Schlosnagle) wrote…</i></summary>
> agreed that seems like it wasn't generated properly before, likely due to #703 . Shouldn't block merging this.
</details>
Ignoring per #703 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713)*

**Comment by schlosna** [comment]
Reviewed 18 of 18 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/713)*

**Comment by tpetracca** [comment]
Sorry for all the weird traffic on this PR.  Dave and I don't quite understand Reviewable.

**Comment by jboreiko** [comment]
I would like to have a justification or path forward for this change in regards to clockforts comments above.  I'm okay having it merged if we have the intention of determining the perf ramifications

**Pull request merged**
