### PR TITLE
Fix/flickering dbkvs tests

### PR DESCRIPTION
**Pull request by SerialVelocity**
---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/809)

### CODE REVIEW

**Comment by gsheasby** [comment]
If checkstyle's happy then I'm happy_with_nit

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresDdlTable.java, line 69 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/809#-KPXNcq_liZRrtR9kzw6:-KPXNcqaYF0bvI4XTXx7:b-l9anw) ([raw file](https://github.com/palantir/atlasdb/blob/480a1eeca695befd27bdfd498f0edc5ac97893d0/atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresDdlTable.java#L69)):*
> ```Java
>                 "already exists");
> 
>         ignoringError(() -> {
> ```

BTW - Optional thing to fix: Borderline "too long for a lambda"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809#-:-KPXNp-E4nC8yc3-fPRI:bk3784m)*

**Comment by SerialVelocity** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresDdlTable.java, line 69 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/809#-KPXNcq_liZRrtR9kzw6:-KPXQEFAfy8GLdMyObGt:bpvxwc4) ([raw file](https://github.com/palantir/atlasdb/blob/480a1eeca695befd27bdfd498f0edc5ac97893d0/atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresDdlTable.java#L69)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> BTW - Optional thing to fix: Borderline "too long for a lambda"
</details>
Not sure I completely agree with that as it's only one SQL query inside the lambda.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809)*

**Comment by gsheasby** [comment]
Reviewed 4 of 6 files at r2.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsKeyValueServiceTest.java, line 53 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/809#-KPXe766LSquL0B9diIS:-KPXe7678W7bMzEUKOwA:b-5dqknu) ([raw file](https://github.com/palantir/atlasdb/blob/1e352c52d44111bb09d2660ee981b288b94f637c/atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsKeyValueServiceTest.java#L53)):*
> ```Java
> 
>     @Test
>     public void testRejectCaseInsensitiveDuplicateTableName() {
> ```

Why was this test deleted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809)*

**Comment by gsheasby** [comment]
Reviewed 1 of 6 files at r2.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809)*

**Comment by SerialVelocity** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsKeyValueServiceTest.java, line 53 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/809#-KPXe766LSquL0B9diIS:-KPXehf3ZXes3gOmSICF:b-w0w4kj) ([raw file](https://github.com/palantir/atlasdb/blob/1e352c52d44111bb09d2660ee981b288b94f637c/atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsKeyValueServiceTest.java#L53)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Why was this test deleted?
</details>
Other KVSs don't throw when this happens. They just ignore it. We also have the problem that we can't throw when this happens because the table creation code doesn't get executed in a transaction so the table can be created in the meantime and it could just mean another atlas client beat us to it (the race condition that this PR fixes).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809)*

**Comment by gsheasby** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/809)*

**Pull request merged**
