### PR TITLE
Add convenience script for parsing server logs

### PR DESCRIPTION
**Pull request by harrybiddle**
On request of @gmaretic. This is especially useful for debugging failed Jepsen tests!

There are a couple of simple tests for this script which I've wired into `./gradlew check`.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1547)

### CODE REVIEW

**Comment by rhero** [comment]
@harrybiddle @gmaretic I'm going to leave this to you guys to prioritize if you think it'll improve your velocity.

**Comment by gmaretic** [comment]
Looks good, thanks!

**Comment by rhero** [comment]
It looks like this is failing its own tests? Can one of you guys take a look at this?

**Comment by harrybiddle** [comment]
Ack. Going to bring this up to date and then see what happens.

**Pull request merged**
