### PR TITLE
Fix/sweep results cells examined (#2830)

### PR DESCRIPTION
**Pull request by mswintermeyer**
* Add test demonstrating SweepResults.getCellTsPairsExamined incorrect

* Fix SweepResults.getCellTsPairsExamined

* Fix CellsToSweepPartitioningIteratorTest use of cellsExaminedSoFar

* update BatchOfCellsToSweep.numCellTsPairsExamined javadoc

* Add release notes

* Fix checkstyle

* Release note: explain the issue that was fixed

**Goals (and why)**:

**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2858)

### CODE REVIEW

**Comment by tboam** [comment]
@gmaretic to review and look at test failures

**Comment by gmaretic** [comment]
This PR is broken because the fix assumes the changes in https://github.com/palantir/atlasdb/pull/2546. Is backporting this high priortiy?

**Comment by mswintermeyer** [comment]
Thanks @gmaretic for figuring out what commit I was missing! I attempted to fix the errors with cherry picking that too. The only conflicts were in CassandraKeyValueServiceImpl. I believe that fixed my test failures, and don't think it added new ones. The error in internal circleci passes for me locally. Regarding priority, it's a P2. No one clamoring for it yet, but a PG LTS uses this version of atlas, so it'd be nice to have sweep info be accurate before someone needs sweep critically.

**Comment by gsheasby** [comment]
Is the problem that this fixes (inaccuracy of cells examined) even known to be an issue on this version of Atlas?

**Comment by gsheasby** [comment]
"* Add test demonstrating SweepResults.getCellTsPairsExamined incorrect"

Did you check that this test also demonstrates `getCellTsPairsExamined` was incorrect to begin with on this version?

**Comment by gmaretic** [comment]
@gsheasby I checked, `testSweepBatchesInDifferentRows` was failing on 0.61.0. The other failing tests were actually passing since the logic that broke them (before they were fixed again) was introduced in the missing commit so the fix actually broke them on the PR. 
Now looks good to me, @gsheasby since you have more SA on sweep, is there anything else that needs to be fixed on this version of sweep? Are we confident cherry picking this commit did not introduce a bug that we later fixed?

**Comment by gsheasby** [comment]
So we've advanced in the chain of sweep PRs, but might still want to go further?

#2610 - ups the default batch size (might not be relevant for the internal product?)
#2732 - fixes an edge case that caused us to page through a lot of deleted data for thoroughly swept tables
#2744 - fixes a corner case introduced by the edge case fix, which results in sweep getting stuck in an infinite loop

Then we'd be down to the OOM fix PRs that are still in progress.

**Comment by gmaretic** [comment]
That makes sense, but seems like we're going down a rabbit hole. Can you weigh in on how we should proceed @tboam ?

**Comment by tboam** [comment]
Definitely want to address the counting issue on the LTS branch as it is broken and confusing.

I agree with cherry picking the commits Glenn mentions as important sweep fixes too.  The sweep OOM fixes should be backported, but I'm happy to wait until we've verified the fixes in the field (demand for OOM fixes is lower on the LTS branch as it is less likely to be affected by Cassandra issues).

Checking the git log for the main sweep classes should reveal any other major changes that should be backported.

**Comment by gsheasby** [comment]
How about the demand for fixing the edge/corner cases? They also only affect Cassandra, so a smaller proportion of LTS consumers will care - but on the other hand, they affect thorough tables, which are more prevalent on the large internal product.

I'd be happy to merge this as-is, and we can continue the chain of backports in later PRs (tiny tasks?)

**Pull request merged**
