### PR TITLE
Add TimeLockStatus.PENDING_ELECTION

### PR DESCRIPTION
**Pull request by fsamuel-bs**
**Goals (and why)**: Add TimeLockStatus.PENDING_ELECTION when no clients have been created.

**Concerns (what feedback would you like?)**: Is it too hacky to expose number of clients as a public method of the resource?

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2939)

### CODE REVIEW

**Comment by fsamuel-bs** [comment]
Lacks tests.

**Comment by fsamuel-bs** [comment]
This should be used by the timelock wrapper to report HEALTHY when NO_CLIENTS are present.

**Comment by tpetracca** [comment]
Why is leader election predicated on the existence of a client. That to me seems to be the core issue here.

**Comment by fsamuel-bs** [comment]
I think that currently, the leader election is a function of the client, i.e. each client creates a timestamp and lock services and wrap them in a AwaitingLeadershipProxy — a proxy that throws if you're not the leader. Changing this would be a much bigger change, and would possibly hinder future optimizations — multiple leaders per cluster (one per client), for example.

This is the minimal change which will bring us what we want, even though a little bit counterintuitive.

**Pull request merged**
