### PR TITLE
Use correct logger class for cassandra request exceptions

### PR DESCRIPTION
**Pull request by pkoenig10**
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3082)

### CODE REVIEW

**Comment by gsheasby** [comment]
@tboam was there a reason to keep the logs using `CassandraClientPoolImpl` when you extracted this class?

**Comment by tboam** [comment]
I didn't want to break anyone's scripts or logging configuration so left messages using the appender they were using before the refactor.  I wasn't aware of any specific scripts or config but was just trying to minimise the breaks.  I'd be happy to break things if there's a note in the changelog.

**Comment by pkoenig10** [comment]
I was motivated to make this change after trying to find the source of a log line. When the log class doesn't match the class where the log line was written, it makes tracing logs take that much longer.

I will add a changelog entry to this PR.

**Comment by gsheasby** [comment]
Closing in favour of #3092 in order to run CI checks.

**Pull request closed without merging**
