### PR TITLE
Test/rename to integration tests

### PR DESCRIPTION
**Pull request by gbrova**
This change does three things: 

- Rename all Cassandra integration tests to end with `IntegrationTest`
- Add `CassandraKeyValueServiceTransactionTest` and `CassandraClientPoolIntegrationTest` to the suite.
- Move the unit tests to a separate package, and ensure they are all actually run

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/896)

### CODE REVIEW

**Comment by gbrova** [comment]
I'm conflicted about whether the unit tests should live in a separate package, or in the same project (and same package) as the actual code.  I actually prefer the latter (per commit [405e0fb](https://github.com/palantir/atlasdb/pull/896/commits/405e0fbc02cf4d8644ccc82fd626d6bd38858663)) but I'm happy to be overruled.

**Comment by gsheasby** [comment]
I like them in the same package. Having a separate integration tests package seems fine to me, and would make it easy to figure out which flavour you're looking at.

Does this PR conflict with #894?

**Comment by gsheasby** [comment]
Reviewed 22 of 57 files at r1, 49 of 49 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-cassandra-integration-tests/build.gradle, line 19 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/896#-KQtnasLI7E6Yr3fj1KR:-KQtnasLI7E6Yr3fj1KS:bdwn1oj) ([raw file](https://github.com/palantir/atlasdb/blob/6697696bb60f261a8fe5a529eae98d3e95f9083e/atlasdb-cassandra-integration-tests/build.gradle#L19)):*
> ```Gradle
> test {
>     maxHeapSize = "1024m"
>     exclude '**/*IntegrationTest*'
> ```

I assume this is to ensure that we only run the tests once from circle?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/896)*

**Comment by gbrova** [comment]
Great, I feel the same way.  Yes, I'd like to merge this first and then rebase #894. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-cassandra-integration-tests/build.gradle, line 19 \[r2\]](https://reviewable.io:443/reviews/palantir/atlasdb/896#-KQtnasLI7E6Yr3fj1KR:-KQtpYEX8wyO7O-zGrJL:b-kbmic7) ([raw file](https://github.com/palantir/atlasdb/blob/6697696bb60f261a8fe5a529eae98d3e95f9083e/atlasdb-cassandra-integration-tests/build.gradle#L19)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> I assume this is to ensure that we only run the tests once from circle?
</details>
These integration tests only run as part of the suite (they don't each start up their own Cassandra cluster). Previously, we got around this by only including tests named `*Suite.class` - but as people added unit tests, those were not getting run. 

After this change, everything except things explicitly named IntegrationTest will run by default.  It shouldn't matter since we're also moving the unit tests to a different package, but it's a little safer in case someone makes a mistake. (Also in general, I think its safer to exclude than include)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/896#-:-KQtpGvGe6y7ypU9DCvD:b5sh8ps)*

**Pull request merged**
