### PR TITLE
[LW] Add tests for LockWatchEventCacheImpl

### PR DESCRIPTION
**Pull request by Jolyon-S**
**Goals (and why)**:
Finish up the string of unit tests for the event cache by testing the event cache impl itself. 

**Implementation Description (bullets)**:
There is _relatively_ little logic in the event cache itself - it mostly just wires the pieces together, and thus these are the parts that are tested in more depth.

**Concerns (what feedback would you like?)**:
One major piece is not explicitly tested: concurrency. Is there a way that we should do this, ideally? I can't think of anything easy (or that I've seen before in the AtlasDB repo short of stress testing).

**Priority (whenever / two weeks / yesterday)**:
It'd be amazing if it was this week!

### CODE REVIEW

**Comment by Jolyon-S** [comment]
> * As you note, concurrency testing isn't really present. We should write a fuzz test at least - admittedly beyond that this is quite tricky. Do you have any other tests in mind?

Is https://github.com/palantir/atlasdb/pull/5722/files#r736345369 sufficient? Or do you want an additional test at this level?

**Comment by jeremyk-91** [comment]
I think we should have an additional test at this level: the correctness of LWECI (in particular the non-synchronization of the two getEvent methods) isn't obvious or trivial from correctness of LWEL I'm afraid

**Comment by jeremyk-91** [comment]
That said, if priority dictates, I'm fine with not doing this right now

**Comment by Jolyon-S** [comment]
> I think we should have an additional test at this level: the correctness of LWECI (in particular the non-synchronization of the two getEvent methods) isn't obvious or trivial from correctness of LWEL I'm afraid

Hah, I misread my own code. I thought this was the stress test in the LWEIT, which does cover this, instead of the LWEL. Fair enough

**Comment by jeremyk-91** [comment]
Agreed.

👍

**Pull request merged**
