### PR TITLE
delete txns on restore relative to commit timestamp

### PR DESCRIPTION
**Pull request by tpetracca**
Per backup engineering review.

@jboreiko @clockfort @tmgordeeva

### CODE REVIEW

**Comment by tpetracca** [comment]
This is going to conflict with https://github.com/palantir/atlasdb/pull/438

**Comment by gbrova** [comment]
Hey @tpetracca what's the status on this?

**Comment by tpetracca** [comment]
I combined this and like 3 of my other PRs into a fork that I've been iterating off of to make backups work at alpha. Will likely have an unfortunately large PR for you guys at some point soon.

**Comment by joelea** [comment]
Cool, will close waiting on that fork.

**Pull request closed without merging**
