### PR TITLE
ClockService should use POST instead of GET

### PR DESCRIPTION
**Pull request by fsamuel-bs**
**Goals (and why)**: Avoid the request result from being cached on the server with POST request.

**Implementation Description (bullets)**: -

**Concerns (what feedback would you like?)**: -

**Where should we start reviewing?**: -

**Priority (whenever / two weeks / yesterday)**: -

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2234)

### CODE REVIEW

**Comment by jnelson15** [comment]
Agreed. I think you can just and `no-cache` and set `max-age` to `-1 `.

**Comment by fsamuel-bs** [comment]
Should fix #2219.

**Comment by fsamuel-bs** [comment]
@schlosna and @jnelson15: does the 1ms also affect us with HTTP2 requests? We use POST everywhere else to avoid caching responses, and I'm trying to assess how would this improve our currently setup.

After talking to the team, we'd rather be consistent and leave POST here, since it's also our pattern everywhere else.

**Comment by nziebart** [comment]
@schlosna I'm reasonable sure the 1ms timeout does not affect http/2 (based on the comment on @jnelson15's PR and based on my own testing, where I've seen http/2 `POST` requests with sub-millisecond latency even from a single thread) - though I don't haven't looked through the okhttp code enough to provide definitive proof.

**Comment by schlosna** [comment]
@nziebart @fsamuel-bs, Yeah, if you're using http2 for this that path avoids setting a 1ms socket timeout to check as [okhttp just checks that the http2 connection is not shutdown](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L512)

From a REST perspective the POST still feels off, but I'll allow it

**Pull request merged**
