### PR TITLE
Bump min version of TimeLock in product dependencies

### PR DESCRIPTION
**Pull request by jeremyk-91**
To quote @gregakinman on #3894 

> 0.58.0's docker image is busted and I'd like to just in my testing say "use the min version specified by atlasdb"

I think this is fine, though we should probably wait for 0.59.0 to be declared stable before doing this, otherwise it might unnecessarily block upgrades

### CODE REVIEW

**Comment by gregakinman** [comment]
makes sense, thanks @jeremyk-91!

**Comment by pkoenig10** [comment]
0.60.0 has been declared stable. Any other blockers to merging this?

**Comment by gregakinman** [comment]
I see there's a conflict but I don't have push perms to this repo so somebody on the team will need to fix it or give me perms

**Comment by gokcanozakdag** [comment]
I'll fix it now

**Pull request merged**
