### PR TITLE
Don't generate final classes

### PR DESCRIPTION
**Pull request by j-baker**
We use a static analysis tool which dings you when you take or
return final classes in your classes, as do many other internal
projects.

It would be good if Atlas were to avoid generating final classes,
since this messes up the static analysis.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/976)

### CODE REVIEW

**Comment by schlosna** [comment]
James, curious why we don't think those warnings are red herrings as these are generated and we probably don't want folks extending them.

**Comment by j-baker** [comment]
I guess for me it's a case of: as a user of Atlas I find that Atlas generated classes don't interact well with the static analysis tools I use. This means that basically all of my Atlas-using constructors are prefixed with

    @SuppressFBWarnings("PT_FINAL_TYPE_PARAM")

which is ugly.

With regard to extension: If you use Baseline you'll trigger FindBugs if you actually extend any of the classes, so I'm not worried there.

I don't feel super strongly about this (easy workaround), except in the case of the StreamStore. Atlas typically pollutes your codebase up to the entry point of the transaction, which is irritating but can be worked around (abstractions and code generation). Additionally, the Atlas interfaces are typically really complicated, so your abstraction is usually drastically simpler.

However, the StreamStore must be used from outside your transaction and has a really simple interface, which means that even high level tests end up needing an InMemory transaction manager or you have to wrap the stream store with something with the same interface. It's sad.

**Comment by schlosna** [comment]
I assume the PT_FINAL_TYPE_PARAM is an internal FindBugs extension, so I'll try to take a look at that. Is the intent of that check to allow for easier testing via injection and mocking? Should we be considering making these interfaces for easier mocking? Would you want to mock all the internals?

**Comment by j-baker** [comment]
Ok, so I looked a bit further, and I think we're ok here. StreamStore is already an interface (PersistentStreamStore), and I discovered a way around findbugs (make the constructor package-private) so we're probably ok there too..

I generally don't think that people should be mocking out AtlasDB generated code. I don't think it's useful in general; imo you should map AtlasDB to your domain and test that with against a KVS.

Findbugs extension; it's at palantir/antipatterns. Fwiw, I tagged you on a PR that adds a new table to my product last night; if you take a look at that you'll see the kind of place where I have to add these suppressions.

**Pull request closed without merging**
