### PR TITLE
Create abstract cli command for when you don't want to or can't init atlas services

### PR DESCRIPTION
**Pull request by tpetracca**
@rjullman to review in immediate term

@joelea / @jboreiko / @clockfort this is so we can do the truncate locks table command (you obviously can't create the actual kvs, but I still want the config)

### CODE REVIEW

**Comment by rjullman** [comment]
👍

**Comment by tpetracca** [comment]
Example of my usage: https://github.com/palantir/atlasdb/tree/feature/truncate-locks-table-cli

**Comment by rjullman** [comment]
You probably shouldn't expose the dagger modules directly and instead expose components.  The issue here is that the dagger magic may not work properly if you are also instantiating things manually (as opposed to having dagger do it).  This particular use case probably won't cause issues since the parsing call is idempotent, but we should probably avoid it.

**Comment by jboreiko** [comment]
@rjullman what are you recommending in this instance.  Seems like an odd use of a dagger module.  Is it worth the overhead to create a dagger instance to generate this class instead of calling create on it directly?

**Comment by tpetracca** [comment]
I think his point was to just not use the dagger stuff if I'm not actually
instantiating the modules, which is why I moved from using a
ServicesConfigModule to an AtlasDbConfig

**Pull request merged**
