### PR TITLE
Optimize getRowsColumnRange

### PR DESCRIPTION
**Pull request by j-baker**
We're seeing perf issues internally on the random getRowsColumnRange
implementation that works better on Postgres and Oracle. This is the way
to make it both simpler, and faster.

This is an alternative to https://github.com/palantir/atlasdb/pull/4326.

Needs tests.

### CODE REVIEW

**Comment by jeremyk-91** [comment]
Ack - I will look at this late today or early tomorrow. Thanks

**Comment by jeremyk-91** [comment]
**Postgres**

Old method

```
Benchmark                                                                                                                                                                           (uri)    Mode  Cnt        Score        Error  Units
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRow                     com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   42   360647.729 ±  16119.913  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithManyUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   35   437555.785 ±  24811.503  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithSomeUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   37   414031.651 ±  13220.436  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsSingleBigRow                          com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   28  5900786.542 ± 165164.916  us/op
```

New method

```
Benchmark                                                                                                                                                                           (uri)    Mode  Cnt        Score         Error  Units
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRow                     com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   43   354382.110 ±   10197.398  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithManyUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   34   446215.349 ±   44773.869  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithSomeUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   37   415377.795 ±   16679.019  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsSingleBigRow                          com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   25  6573984.317 ± 2170410.658  us/op
```

I had difficulty getting the Cassandra benchmarks to work properly (some issues with MGMS). Is the perf improvement expected more in that and/or in some case our benchmarks don't test?

**Comment by mswintermeyer** [comment]
The hope was to improve perf for a situation when calling getRowsColumnRange across many rows, but where each have just ~1 column each. Previously we'd fallback to the BatchSizeIncreasingIterator which would throw away the original iterator and create a new one regularly, and each time creating a new one would mean validating the locks are still valid.

**Comment by jeremyk-91** [comment]
Cool. I added a test that features a long and narrow table with 1 million rows and 1 column. Also added a 2 milli penalty for a lock check to simulate using timelock. Then,

new
```
Benchmark                                                                                                                                    (uri)    Mode  Cnt       Score      Error  Units
TransactionGetRowsColumnRangeBenchmarks.jeremyTest  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample  804  111896.851 ± 4578.068  us/op
```

old
```
Benchmark                                                                                                                                    (uri)    Mode  Cnt         Score         Error  Units
TransactionGetRowsColumnRangeBenchmarks.jeremyTest  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample    4  23412604.928 ± 3275831.242  us/op
```

**Comment by jeremyk-91** [comment]
With 2 ms penalty for timelock ops:

new
```
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRow                     com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   40   380003.942 ±  14246.615  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithManyUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   34   451134.404 ±  15757.661  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithSomeUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   35   437810.439 ±  18242.531  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsSingleBigRow                          com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   27  6049739.814 ± 175294.550  us/op

@mswintermeyer I think all of these benchmarks only have one row, though, so the improvement in terms of reducing the number of lock checks would not be significant.
```

old
```
Benchmark                                                                                                                                                                           (uri)    Mode  Cnt        Score        Error  Units
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRow                     com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   40   375875.174 ±  17092.756  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithManyUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   33   459308.063 ±  27465.031  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsModeratelyWideRowWithSomeUncommitted  com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   35   432088.210 ±  14429.160  us/op
TransactionGetRowsColumnRangeBenchmarks.getAllColumnsSingleBigRow                          com.palantir.atlasdb.performance.backend.PostgresKeyValueServiceInstrumentation@127.0.0.1:5432  sample   26  6184339.929 ± 194572.677  us/op
```

**Pull request merged**
