### PR TITLE
Remove the overflowMigrationState

### LINKED ISSUE #977: Overflow migration for Oracle is not required
Overflow stuff is a way of defining where large data cells in Oracle go (over some configurable threshold size), which allows Atlas to keep range read performance up and it looks like we use a DB sequence to assign unique IDs to the overflow segments.

OSS Atlas did not have support for oracle in the past and does not need to support migration from ``singleOverflowTable`` to an overflow table per table. We will start with having overflow tables for each table separately.

### PR DESCRIPTION
**Pull request by hsaraogi**
Fixes #977.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/978)

### CODE REVIEW

**Comment by clockfort** [comment]
AFAIK you can't remove all of this from Atlas just yet, unless you remove it in such a way that it is pluggable, such that PG can take this code into itself and is still able to provide an overflow getter method so it can provide the old one for unmigrated customers.

The current peeps associated with people still on the old way are
@berler @gbonik and @tkleingarnWhoDoesntHaveAGithubAccountApparentlyUgh
They need to agree on a release timeframe when they can force everyone onto the new overflow system, and then all of this can get really really deleted. (It's possible said force-everyone-onto-latest-overflow release has already passed and I just don't know, I'm not well-connected with them now)

**Comment by hsaraogi** [comment]
Waiting for peeps to finish overflow migrations.

**Comment by jboreiko** [comment]
@clockfort thanks for the heads up, are these migrations being tracked anywhere?  I guess I'm wondering what the timeline of it will be.

**Comment by gbonik** [comment]
@jboreiko I think @tkleingarnWhoDoesntHaveAGithubAccountApparentlyUgh has the list of migrations that need to be done

**Comment by tkleingarn** [comment]
Not hard numbers, but I think we have roughly 30 more deployments that would need to perform overflow table migrations before we can delete this code.

**Pull request closed without merging**
