### PR TITLE
AtlasDB CLI dropwizard bundle

### PR DESCRIPTION
**Pull request by SerialVelocity**
Left to do: 
  - [x] ETE tests for AtlasDbCliCommand
  - [ ] Unit tests for AtlasDbCliCommand
  - [x] ETE tests for AtlasDbConsoleCommand (maybe blocked on console refactor?)
  - [ ] Unit tests for AtlasDbConsoleCommand (blocked on console refactor)
  - [x] Release notes for dropwizard bundle

This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/696)

### CODE REVIEW

**Comment by jboreiko** [comment]
Reviewed 3 of 7 files at r1, 7 of 10 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: 11 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 55 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI5Jk07_nlBMU8E72O:-KNI5Jk07_nlBMU8E72P:-176065738) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L55)):*
> ```Java
>             try {
>                 if (configFile != null) {
>                     config = AtlasDbConfigs.load(configFile, configRoot);
> ```

nit: want indication of nullability here, added in commit

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 69 \[r5\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI6HBqMTaRWLA5Q1A8:-KNI6HBrivhkOpqWONPt:401500300) ([raw file](https://github.com/palantir/atlasdb/blob/8ee3b4d8c5a67dcaf343ef195f750baca6e64aeb/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L69)):*
> ```Java
>                 }
>                 if (offline) {
>                     config = ImmutableAtlasDbConfig.builder()
> ```

This prevents us from doing the safety checks that look for the up endpoints of other services which would indicate that offline is not safe

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java, line 220 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNHw4CCZ6vElfaY_a9T:-KNHw4CCZ6vElfaY_a9U:-897551254) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L220)):*
> ```Java
>             warnIf(config.lock().isPresent() != config.timestamp().isPresent(), "Using embedded instances for one (but not both) of lock and timestamp services");
> 
>             RemoteLockService lockService = config.lock().transform(new ServiceCreator<>(sslSocketFactory, RemoteLockService.class)).or(lock);
> ```

In case it's unclear I've added the don't merge since this is on the back of that other PR.

---

*[atlasdb-dropwizard-bundle/build.gradle, line 4 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNHwASLpX8eTkQtrHB6:-KNHwASLpX8eTkQtrHB7:1624134054) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-dropwizard-bundle/build.gradle#L4)):*
> ```Gradle
> 
> dependencies {
>     compile(project(':atlasdb-cli')) {
> ```

This is a bummer, I'm wondering if we should take a moment to reduce our dep footprint since I suspect that we could do a bit better, especially in regards to our cassandra dependency.  After having a little chat with some folks, another solution here to stem the dep growth would be to have a dependency lock file that requires a manual override to increase the dep footprint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by SerialVelocity** [comment]
Review status: 11 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 55 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI5Jk07_nlBMU8E72O:-KNIEf5ns6JANViQ07QH:-1377417289) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L55)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> nit: want indication of nullability here, added in commit
</details>
Not sure I understand what you mean by this.

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 69 \[r5\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI6HBqMTaRWLA5Q1A8:-KNIEI9Stu75MXzqHlbD:1127822992) ([raw file](https://github.com/palantir/atlasdb/blob/8ee3b4d8c5a67dcaf343ef195f750baca6e64aeb/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L69)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This prevents us from doing the safety checks that look for the up endpoints of other services which would indicate that offline is not safe
</details>
Yes, this is just a way for users to explicitly say that the cli is running in offline mode so they don't accidentally start a migration on a running cluster because they didn't realise they had to shut it down. Adding safety checks is something we should do later instead of in this PR so that this PR doesn't become huuuuuge.

---

*[atlasdb-dropwizard-bundle/build.gradle, line 4 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNHwASLpX8eTkQtrHB6:-KNIEsAU52Bnpr_kXA2d:1402590789) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-dropwizard-bundle/build.gradle#L4)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This is a bummer, I'm wondering if we should take a moment to reduce our dep footprint since I suspect that we could do a bit better, especially in regards to our cassandra dependency.  After having a little chat with some folks, another solution here to stem the dep growth would be to have a dependency lock file that requires a manual override to increase the dep footprint.
</details>
Most of these have to be excluded because the dependencies pulled in by cassandra and dropwizard conflict. We should do something about this but should we do it before this PR goes in? I think after may be better and we should go through the whole codebase and sort everything out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by gsheasby** [comment]
Review status: 10 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java, line 220 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNHw4CCZ6vElfaY_a9T:-KNgn9Ju7EQOARBfD-V_:-1025924770) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L220)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> In case it's unclear I've added the don't merge since this is on the back of that other PR.
</details>
...which has now merged :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by tpetracca** [comment]
@SerialVelocity how we doing here?

**Comment by SerialVelocity** [comment]
It was passed over to Glenn, but since he's on an aeroplane today I've taken it over again since John and I want to merge it before hack week. I've written a few online ETE tests and with a few more of those plus a few unit tests for the utility functions, we should be good to go!

**Comment by jboreiko** [comment]
Reviewed 1 of 7 files at r1, 3 of 10 files at r3, 2 of 3 files at r6, 1 of 4 files at r7, 25 of 25 files at r8.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java, line 153 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPF7_da55v_RFXjNXPP:-KPF7_da55v_RFXjNXPQ:bssq5z8) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java#L153)):*
> ```Java
>     @Value.Derived
>     public boolean usingSsl() {
>         return ssl().or(false) || sslConfiguration().isPresent();
> ```

This should not be a part of this PR and should be removed once develop has been updated and this has been rebased onto it, referring to #768 

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 55 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI5Jk07_nlBMU8E72O:-KPF8IirRSEjOyZGLb3T:b9cs1e9) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L55)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> Not sure I understand what you mean by this.
</details>
I found it confusing to see that configRoot could be null with no indication that this is the case until 4 methods down in AtlasDbConfigs#findRoot where you see a null check 
```
if (Strings.isNullOrEmpty(configRoot)) {
           return node;
}
```

---

*[atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java, line 101 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFG-LnxTOewVy-dzkm:-KPFG-Lom4aSCtqGwIA8:b56gf3c) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java#L101)):*
> ```Java
>     @JsonIgnore
>     @Value.Default
>     public Visitor<Connection> getOnAcquireConnectionVisitor() {
> ```

nit: Might be worth mentioning in a comment the serialization problems that lead to this ignore

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/AtlasDbConfiguredCommand.java, line 51 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFim42DDFDbKkRUTdd:-KPFim43_RaaiHzMlVKB:bkw04uh) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/AtlasDbConfiguredCommand.java#L51)):*
> ```Java
>     @Override
>     public void configure(Subparser subparser) {
>         Subparser parser = subparser.addSubparsers()
> ```

To confirm this code establishes a default console parsing if no arguments are provided?

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 58 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFlm42vY_tTbZd-CyE:-KPFlm44x-0Q6YP6XkQe:bz6uct9) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L58)):*
> ```Java
> 
>     static {
>         YAMLFactory yamlFactory = new YAMLFactory();
> ```

Duplicate code with AtlasDbConsoleCommand, can we make a shared method

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 69 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFix35S_7WIBqVtFkW:-KPFix35S_7WIBqVtFkX:b-euohvf) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L69)):*
> ```Java
> 
>     @Override
>     public void configure(Subparser subparser) {
> ```

This does call the super method to add the offline cli option is that intentional?  If so why not move the offline parser logic into the console command?

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 84 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFmx8lFS0HX07WpyWf:-KPFmx8lFS0HX07WpyWg:bps50be) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L84)):*
> ```Java
>     }
> 
>     private void addCommandToParser(Subparser subparser, CommandMetadata subCommand, List<String> commandRoot) {
> ```

This looks sufficiently complex to be unit tested as is and/or broken into smaller methods to be further unit tested.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 149 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFpauAZVtYvIrLNrLn:-KPFpauAZVtYvIrLNrLo:b-fipue0) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L149)):*
> ```Java
>     }
> 
>     private static Map<String, OptionType> getCliOptionTypes() {
> ```

Seems very similar to configure minus the injection into the subparser, could be valuable to combine the two, also would like to see some unit testing here.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java, line 40 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFspYEi5n3h8YmjlyT:-KPFspYEi5n3h8YmjlyU:b-oy5x0m) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java#L40)):*
> ```Java
> 
>     public static AtlasDbConfig convertServerConfigToClientConfig(AtlasDbConfig serverConfig) {
>         Preconditions.checkArgument(serverConfig.leader().isPresent(), "Only server configurations with a leader block can be converted to client configurations");
> ```

Should we add a check to confirm that the config does not include lock / timestamp blocks?  Doesn't appear to ever be checked and rejected if there, only a warning logged on start up of the service.  I may be wrong, but I tough we now considered them fully deprecated.

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml, line 35 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFuwHXdZANi9hgV-D0:-KPFuwHXdZANi9hgV-D1:bituyf) ([raw file](https://github.com/palantir/atlasdb/blob/11f72d2bb35dcde2dcd0cdc1b8e802939372449b/atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml#L35)):*
> ```YAML
>     acceptorLogDir: var/data/paxosLog/acceptor1
>     localServer: http://${ME}:3828
>     lockCreator: http://ete1:3828
> ```

Does removing this hinder our testing of the lockCreation logic (though notably it does simply delegate to the top of the leader list)

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml, line 30 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFvTLQo29pTUMXei3R:-KPFvTLQo29pTUMXei3S:b-u2hd70) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml#L30)):*
> ```YAML
>     autoRefreshNodes: false
> 
>   leader:
> ```

This 'no-leader' test appears to have a leader block

---

*[atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java, line 60 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFw1fS-LmHuHSRCqSG:-KPFw1fS-LmHuHSRCqSH:b-dkbohy) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java#L60)):*
> ```Java
>     }
> 
>     protected String runCommand(String command) throws IOException, InterruptedException {
> ```

This is pretty cool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by SerialVelocity** [comment]
Review status: 30 of 38 files reviewed at latest revision, 11 unresolved discussions.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java, line 153 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPF7_da55v_RFXjNXPP:-KPHl3ylzpKU_Xve3Wk3:bb6un1j) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java#L153)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This should not be a part of this PR and should be removed once develop has been updated and this has been rebased onto it, referring to #768 
</details>
Done

---

*[atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java, line 55 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KNI5Jk07_nlBMU8E72O:-KPHlKBht4X0SAJTmOyb:b-id6rxg) ([raw file](https://github.com/palantir/atlasdb/blob/cf553805e52e7cebcd1b187cabf6c5a1da0539dd/atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java#L55)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> I found it confusing to see that configRoot could be null with no indication that this is the case until 4 methods down in AtlasDbConfigs#findRoot where you see a null check 
> ```
> if (Strings.isNullOrEmpty(configRoot)) {
>            return node;
> }
> ```
</details>
Done. Added `@Nullable` all the way down the tree.

---

*[atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java, line 101 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFG-LnxTOewVy-dzkm:-KPHpLqGb6g0oiQJSxKo:bb6un1j) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java#L101)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> nit: Might be worth mentioning in a comment the serialization problems that lead to this ignore
</details>
Done

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/AtlasDbConfiguredCommand.java, line 51 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFim42DDFDbKkRUTdd:-KPHnSuroRPpSX5W8dOP:bshui9h) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/AtlasDbConfiguredCommand.java#L51)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> To confirm this code establishes a default console parsing if no arguments are provided?
</details>
Not sure exactly what you mean by this. This sets up the "console" command. We then pass the whole subparser to cliCommand to set up all of the other commands.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 58 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFlm42vY_tTbZd-CyE:-KPIDoj8dWgukB9DwH2C:bb6un1j) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L58)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Duplicate code with AtlasDbConsoleCommand, can we make a shared method
</details>
Done

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 69 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFix35S_7WIBqVtFkW:-KPHntsVSe1kv21Y4QYH:bph21sn) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L69)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This does call the super method to add the offline cli option is that intentional?  If so why not move the offline parser logic into the console command?
</details>
It is intentional. We use the parameter below in `run`.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 84 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFmx8lFS0HX07WpyWf:-KPI2_Hg4Aqtsk9xnlih:bb6un1j) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L84)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This looks sufficiently complex to be unit tested as is and/or broken into smaller methods to be further unit tested.
</details>
Done

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 149 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFpauAZVtYvIrLNrLn:-KPHq5lf0ccMc8WU9PXt:bbea2p9) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L149)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Seems very similar to configure minus the injection into the subparser, could be valuable to combine the two, also would like to see some unit testing here.
</details>
This is used at runtime rather than configure-time so it's super hard to combine since we don't want to run all the other logic when doing this. I won't add unit testing to this, but to one layer down (to `getOptionTypesForCommandMetadata`) which is where all of the logic is.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java, line 40 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFspYEi5n3h8YmjlyT:-KPHmt2hXFneonH9eICg:b-ov9bz6) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java#L40)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Should we add a check to confirm that the config does not include lock / timestamp blocks?  Doesn't appear to ever be checked and rejected if there, only a warning logged on start up of the service.  I may be wrong, but I tough we now considered them fully deprecated.
</details>
If we do that, I don't think it should be done here. We should make the AtlasDbConfig check that both the leader block and timestamp/lock blocks are not defined at the same time.

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml, line 35 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFuwHXdZANi9hgV-D0:-KPHm1Gh3G1l6AYK48WU:bdjqg4u) ([raw file](https://github.com/palantir/atlasdb/blob/11f72d2bb35dcde2dcd0cdc1b8e802939372449b/atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml#L35)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Does removing this hinder our testing of the lockCreation logic (though notably it does simply delegate to the top of the leader list)
</details>
No, it doesn't. We don't test the lockCreation logic here at all.

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml, line 30 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFvTLQo29pTUMXei3R:-KPHldfGllqfW3GUlV6n:b2r6o3y) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml#L30)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This 'no-leader' test appears to have a leader block
</details>
This is what we use when running the CLIs or console. The server doesn't run with this config.

---

*[atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java, line 60 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFw1fS-LmHuHSRCqSG:-KPHoEQ2wghAGMFV8-xl:bim82qs) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java#L60)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> This is pretty cool
</details>
Shame we can't use exec though!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by jboreiko** [comment]
Reviewed 11 of 12 files at r9, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java, line 69 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFix35S_7WIBqVtFkW:-KPKmXMs3CNhRzEwhutu:bv1iu2z) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCliCommand.java#L69)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> It is intentional. We use the parameter below in `run`.
</details>
OK I see that call to configure now.

---

*[atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java, line 40 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFspYEi5n3h8YmjlyT:-KPKn4EW8jtif5_k-ZH8:b-sw3ob5) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-dropwizard-bundle/src/main/java/com/palantir/atlasdb/dropwizard/commands/AtlasDbCommandUtils.java#L40)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> If we do that, I don't think it should be done here. We should make the AtlasDbConfig check that both the leader block and timestamp/lock blocks are not defined at the same time.
</details>
OK, I agree file #790

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml, line 35 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFuwHXdZANi9hgV-D0:-KPKpyDxOF7PJ9q6WDfH:b5kht6w) ([raw file](https://github.com/palantir/atlasdb/blob/11f72d2bb35dcde2dcd0cdc1b8e802939372449b/atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml#L35)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> No, it doesn't. We don't test the lockCreation logic here at all.
</details>
By changing this configuration you will now default the lockCreator to the first host in the leader block which is fine but means our ETE tests aren't run with our supported config of lockCreator

---

*[atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml, line 30 \[r8\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPFvTLQo29pTUMXei3R:-KPKqQLr0uuDe4WoLxuG:bce4pr2) ([raw file](https://github.com/palantir/atlasdb/blob/afbf538d44a47a03a96c174a8c42dfb49d6685a8/atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml#L30)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> This is what we use when running the CLIs or console. The server doesn't run with this config.
</details>
OK I missed the client.yml ending there wondering if it's worth adding a comment there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Comment by jboreiko** [comment]
Reviewed 2 of 2 files at r11, 2 of 2 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-ete-tests/docker-compose.dbkvs.yml, line 13 \[r12\]](https://reviewable.io:443/reviews/palantir/atlasdb/696#-KPTl3RPNekdgRkd3bIH:-KPTl3RPNekdgRkd3bII:bgj0m3d) ([raw file](https://github.com/palantir/atlasdb/blob/62cf39e1449f4f166e493d9b28d5666d9d4403fd/atlasdb-ete-tests/docker-compose.dbkvs.yml#L13)):*
> ```YAML
>       - "5432"
> 
>   ete1:
> ```

why don't any of these have the depends_on block?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/696)*

**Pull request merged**
