### PR TITLE
type safely -> type safety

### PR DESCRIPTION
**Pull request by bfab**
It looks like a typo.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/950)

### CODE REVIEW

**Comment by joelea** [comment]
Thanks!

**Comment by bfab** [comment]
Not sure whether I need to do anything to make circleci happy though. Shall I leave it to you?

**Comment by joelea** [comment]
Ah, sorry. The right place to do this is actually on the main develop branch in the docs directory, that gets build and published to gh-pages as part of the build. It means that code and docs can be merged as part of the same PR.

I'm happy to fix it there myself, or feel free to do it.

**Comment by bfab** [comment]
Cool. I'll do it myself, thanks for clarifying!

**Comment by bfab** [comment]
hmm... can't find any occurrence of "type safely" on the develop branch though. Can you figure out where that sentence comes from in the code?

**Comment by joelea** [comment]
There was some confusion on my part, this is fine for this particular page. All merged. Thanks for the PR!

**Comment by bfab** [comment]
Cool, thanks for assisting!

**Pull request merged**
