### PR TITLE
Add cassandra drivers to atlasdb-cli

### PR DESCRIPTION
**Pull request by leeavital**
- [x] Someone has been assigned to review this PR

**Reason for change**
- This allows the `atlasdb-cli` to talk to Cassandra.

### CODE REVIEW

**Comment by leeavital** [comment]
I think @glentakahashi used this successfully.

**Comment by rjullman** [comment]
There is an open question here about how we want to have these underlying kvs dependencies included here.  If with go with this approach we will have an atlas-cli that has drivers for everything when applications only need to use one.  This may be question outside of the scope of this PR (perhaps we have to refactor a bunch of things).

**Comment by leeavital** [comment]
> with this approach we will have an atlas-cli that has drivers for everything when applications only need to use one

I'm not so sure that's a problem.  Most applications ship with multiple atlas drivers (rocksdb, cassandra, and sometimes JDBC/postgres) in order to get stuff to work out of the box with any setup. 

On the other hand, keeping the size of the distribution small is much more important for a CLI.

**Comment by joelea** [comment]
This seems entirely reasonable, but @rjullman your concerns seem totally valid. We likely need some chunkier refactorings to do that, and I'm not sure this change will make those refactorings any harder.

**Comment by rjullman** [comment]
@leeavital To clarify what I was saying, I was not particularly concerned with how many drivers each deployment ships with, but just that each deployment already ships with these drivers and they should be added by that deployment's atlas cli instead of included by default in the atlas-cli build.  This can hopefully be handled by the mythical atlas gradle plugin (in progress).

I'm happy enough to merge this if people are hitting this as an issue.  That said, we should probably revert this change when the atlas plugin works.

**Pull request merged**
