### PR TITLE
Validate connections from Hikari

### PR DESCRIPTION
**Pull request by hsaraogi**
**Goals (and why)**: Fix QA-99787.

**Implementation Description (bullets)**: Mostly copied from #2142 and addressed comments.

**Concerns (what feedback would you like?)**: There is some overhead when getting a connection form the hikari pool (running a test query), can this cause significant perf hit?

**Where should we start reviewing?**: One file.

**Priority (whenever / two weeks / yesterday)**: one-two days.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2301)

### CODE REVIEW

**Comment by davidscottcohen** [comment]
LGTM

**Comment by davidscottcohen** [comment]
Make sure to backport this for 0.39.x for PG 3.14 LTS

**Comment by schlosna** [comment]
Do we have benchmark numbers for comparison on Postgres as well? I'm still a bit concerned about the overhead of testing connection on acquiring thread, and wondering if we should be doing the test on an async thread when returning the connection to the pool

**Comment by hsaraogi** [comment]
@schlosna we do have benchmarks for Postgres covering KVS level operations and sweep. Do you think its worth adding benchmarks for getting a new connection from the pool?

**Comment by davidscottcohen** [comment]
I ran benchmarks against PGDev with the patch.  Seems fine.  Async validation might be a good FR but we should not block the commit on this.  Let's get this merged ASAP so we make sure to get testing on it in PG 3.15.0 before we go and ship the PG 3.15 LTS.

**Pull request merged**
