### PR TITLE
Treat NotCurrentLeaderException as an AtlasDbDependencyException

### PR DESCRIPTION
**Pull request by gsheasby**
**Goals (and why)**: If `NotCurrentLeaderException` is thrown up to the Atlas layer, then it means no Timelock node believes itself to be the leader. We will not be able to talk to TimeLock until this is resolved (usually a few seconds), so we throw AtlasDbDependencyException.

**Concerns (what feedback would you like?)**: To do this, I needed to add a dependency: `lock-api` now depends on `leader-election-api`. Both projects have pretty small dependency footprints, though.

**Where should we start reviewing?**: The java files (the java part is ~10 lines and mostly test)

**Priority (whenever / two weeks / yesterday)**: Before release, but not necessarily over QoS stuff.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2716)

### CODE REVIEW

**Comment by hsaraogi** [comment]
*[lock-api/build.gradle, line 16 at r1](https://reviewable.io:443/reviews/palantir/atlasdb/2716#-KzP-Cqrd4f-y5n2wh2N:-KzP-Cqrd4f-y5n2wh2O:b-56icdi) ([raw file](https://github.com/palantir/atlasdb/blob/399f79c2ff2075eb0cbfb99c38230b970ba71a26/lock-api/build.gradle#L16)):*
> ```Gradle
> dependencies {
>     compile project(":atlasdb-commons")
>     compile project(":leader-election-api")
> ```

nit: This is odd, can we move the AtlasDbDependencyException class around (probably to a module with common stuff) to not create a dependency explosion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2716)*

**Comment by hsaraogi** [comment]
*[lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java, line 124 at r1](https://reviewable.io:443/reviews/palantir/atlasdb/2716#-KzP-jpzljovzq5JFO4s:-KzP-jpzljovzq5JFO4t:bg6dplk) ([raw file](https://github.com/palantir/atlasdb/blob/399f79c2ff2075eb0cbfb99c38230b970ba71a26/lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java#L124)):*
> ```Java
>                     || e.getCause() instanceof UnknownHostException
>                     || e.getCause() instanceof NotCurrentLeaderException) {
>                 throw Throwables.unwrapAndThrowAtlasDbDependencyException(e);
> ```

Should NCLE just be a sublass of AtlasDbDependencyException?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2716)*

**Comment by hsaraogi** [comment]
*[lock-api/src/test/java/com/palantir/lock/client/TimeLockClientTest.java, line 169 at r1](https://reviewable.io:443/reviews/palantir/atlasdb/2716#-KzP022czLu4h-8_CRud:-KzP022czLu4h-8_CRue:b-3h0dv0) ([raw file](https://github.com/palantir/atlasdb/blob/399f79c2ff2075eb0cbfb99c38230b970ba71a26/lock-api/src/test/java/com/palantir/lock/client/TimeLockClientTest.java#L169)):*
> ```Java
>     public void throwsDependencyUnavailableWhenDelegateIsUnknown() {
>         Throwable cause = new UnknownHostException("I don't know how to talk to TimeLock");
>         Throwable exceptionToThrow = new RuntimeException(cause);
> ```

nit: these tests can be refactored as they test the same thing for different exception causes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2716)*

**Comment by hsaraogi** [comment]
Reviewed 28 of 28 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2716)*

**Comment by gsheasby** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lock-api/build.gradle, line 16 at r1](https://reviewable.io:443/reviews/palantir/atlasdb/2716#-KzP-Cqrd4f-y5n2wh2N:-KzP0C-giv4o-d0rbCro:bx8c7x2) ([raw file](https://github.com/palantir/atlasdb/blob/399f79c2ff2075eb0cbfb99c38230b970ba71a26/lock-api/build.gradle#L16)):*
<details><summary><i>Previously, hsaraogi (Himangi Saraogi) wrote…</i></summary><blockquote>

nit: This is odd, can we move the AtlasDbDependencyException class around (probably to a module with common stuff) to not create a dependency explosion?
</blockquote></details>

The problem is not with `AtlasDbDependencyException`, but with `NotCurrentLeaderException`, which lives in `leader-election-api`.

To resolve this without changing dependencies, we could move `NotCurrentLeaderElection` down to `atlas-commons`, which is the only common dependency between `leader-election-api` and `lock-api`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/2716)*

**Pull request merged**
