### PR TITLE
Cleanup/remove expiring stream store

### PR DESCRIPTION
**Pull request by clockfort**
This isn't random cleanup, this is an out-with-the-old and in-with-the-new kind of thing.
This simplifies the code to make it easier for us to add in better (client-side, not db-side) compressed stream support, which is a feature we actually want currently.

We don't use expiring stream stores, which I added because someone said they needed it (they ended up not using it).
I don't like any of the expiring stuff in general, but there is a ❄️ that uses it so the actual Cell-based expiring code cannot be removed currently.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1051)

### CODE REVIEW

**Comment by clockfort** [comment]
Also, seems like someone was previously bad and fixed up some class ordering but didn't re-render the generated code they touched.

**Comment by clockfort** [comment]
Assigned boreiko because he likes code-tours-via-mass-deletion. Feel free to re-assign.

**Comment by jboreiko** [comment]
What cell-based expiring logic are you referring to? and why can't we remove it?  Otherwise this PR looks good.  -(pr: needs review) 

---

Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1051#-:-KUDAWIylgJ6d9Si9qdL:bexf5e2)*

**Comment by schlosna** [comment]
@jboreiko the existing cell expiration is specified at the Cell level in the constructor: https://github.com/palantir/atlasdb/blob/develop/atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Cell.java#L84 and is used by at least one internal project for TTLing cells

**Pull request merged**
