### PR TITLE
disallow multiple tables in C* with different casing

### PR DESCRIPTION
**Pull request by rjullman**

### CODE REVIEW

**Comment by joelea** [comment]
Are we in a place where we can add a unit test for this?

**Comment by rjullman** [comment]
Definitely possible, but I'm sure it will fail all the other KVSs.  For now I'm happy to just push this through because it also fixes a correctness issue with dropTables on C*.  Also we need to define our KVS spec.  For example, this code here also applies to Namespaces which are somewhat outside the scope of the KVSs.  Perhaps we can fix this by only allowing lower case namespaces? or maybe applying this over all namespaces has the intended effect (if you try to have namespaces with different casing only one namespace will work effectively)?  Thoughts?

**Comment by joelea** [comment]
Ok, now I have looked at that class, I see writing a unit test for C*Kvs to check this is not going to happen. I was looking for that rather than some addition to AbstractKeyValueServiceTest.

**Comment by rjullman** [comment]
Sounds good to me.  Will do.  Just noticed that we actually don't run our abstract kvs tests against C* at all?!?  I'll fix that here too.

**Comment by rjullman** [comment]
Updated.  Also made a ticket for the stricter specification https://github.com/palantir/atlasdb/issues/325.

**Comment by tpetracca** [comment]
What's the context for this?

**Comment by rjullman** [comment]
@tpetracca You can't have non-lower-case tables in C* without this change.

**Comment by jboreiko** [comment]
@nemines / @joelea - this test failure looks related to the switch to dockerized ete.

**Comment by nemines** [comment]
@jboreiko yes, the new test is trying to connect to cassandra on localhost instead of the container. The test should not create its own keyValueService, but using the one in CassandraTestSuite.

**Comment by clockfort** [comment]
lgtm, feel free to merge, but I would also like javadoc documentation update of KeyValueService.java to make this part of the contract for createTable

**Comment by gracew** [comment]
sweet! now that this has merged, can we cut a new release?

**Comment by joelea** [comment]
There have been a couple of hiccoughs with the release, but we're working on it as we speak. Will notify people when it's ready.

**Pull request merged**
