### PR TITLE
Only log detailed logs if DEBUG enabled

### PR DESCRIPTION
**Pull request by mglazer**
**Goals (and why)**:

Saw this trace in a hot code path

**Implementation Description (bullets)**:

Add if statement.

**Testing (What was existing testing like?  What have you done to improve it?)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

Next week

### CODE REVIEW

**Comment by carterkozak** [comment]
lgtm once the changelog is updated

**Review by schlosna — APPROVED** [review]

**Comment by jeremyk-91** [comment]
I updated the changelog

**Review by Jolyon-S — APPROVED** [review]

**Comment by mglazer** [comment]
Is this test flaky?

**Comment by Jolyon-S** [comment]
> Is this test flaky?

yes, very. There is a PR up to fix it.

**Comment by jeremyk-91** [comment]
yeah, that's https://github.com/palantir/atlasdb/pull/5329

**Pull request merged**
