### PR TITLE
Reap by immutable timestamp

### PR DESCRIPTION
**Pull request by mswintermeyer**
**Goals (and why)**:

**Implementation Description (bullets)**:

**Testing (What was existing testing like?  What have you done to improve it?)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

### CODE REVIEW

**Comment by j-baker** [comment]
Please can we get a test for the behaviour that was clearly broken before this PR but that works after this PR?

**Comment by clockfort** [comment]
> Placing the token on the queue says that you don't want to unlock it now but want to consider it again later, basically, so #4181 didn't change the reaping directly. After this change, it definitely looks like we do execute reaping.

That's why #4181 doesn't place it back on the queue and elects to just log and not place it back on the queue

**Comment by clockfort** [comment]
I looked into writing a test for this; the tests for the old old lock server whose behaviour is being modified here seem to be almost non existent and just smoke and logging tests 😞

**Comment by j-baker** [comment]
Ok, but because of that your change no-opped and the customer still had a broken stack

**Pull request merged**
