### PR TITLE
Check #servers > RF

### PR DESCRIPTION
**Pull request by leeavital**

### CODE REVIEW

**Comment by clockfort** [comment]
On the fence.
This check is already done by CassandraVerifier#sanityCheckDatacenters() , but your check is better in that it fails slightly quicker and in a more obvious place.

Your change might make more annoying some weird disaster recovery workflows or cases where people are explicitly relying on another CKVS feature, automatic node discovery, which allows a user to specify less than all of their servers in the atlas conf and have us autodiscover the rest using the coordinator(s) specified as sort of a seed.

**Comment by leeavital** [comment]
Ah that makes sense. Would it make sense to make the failure more explicit in `sanityCheckDatacenters`? I hear that the failure you get is not to clear unless you know about the guts of the CKVS.

**Comment by clockfort** [comment]
I would completely believe that is true.

**Comment by tpetracca** [comment]
Was there something specific that sparked wanting to add this?  I'm inclined to not add it for the reasons CLock mentions above.  sanityCheckDatacenters has the added benefit of being able to be supressed via safetyDisabled flag in the config.  Let's just make that clearer / more explicit?

**Comment by leeavital** [comment]
We have some configs that set the default RF to three.  Someone tried to
start with only one Cassandra node and didn't figure out the problem from
the existing message. We would rather leave the RF to three to prevent
foot-shooting.

I'll take a look at sanityCheckDatacenters.

**Comment by clockfort** [comment]
#291 from tpetracca taken

**Pull request closed without merging**
