### PR TITLE
Bump http-remoting everywhere to remoting2

### PR DESCRIPTION
**Pull request by tpetracca**
**Goals (and why)**:
To bump to remoting2 so it's easier to use other Palantir infrastructure.

**Implementation Description (bullets)**:
I split the work into two commits. The first is all of the actual changes, which is largely just `build.gradle` minor changes, and renames of imports in java files. The 2nd commit is all of the `version.lock` changes. Hopefully that makes it easier to review?

**Concerns (what feedback would you like?)**:
I generally spot-checked that all of the changes made are safe to make, but here's a quick summary of it all:
- Configuration stuff like `SslConfiguration` and `SslSocketFactories` - should be safe to bump; in most cases these things are identical
- Tracing stuff like `Tracers`, `Span`, etc. - I'm less familiar with this stuff and didn't scan the diffs, but it should be safe to bump. @schlosna to confirm.
- Clients stuff
  - `UserAgents` - a few things in the [diff](https://github.com/palantir/http-remoting/commits/develop/http-clients-api/src/main/java/com/palantir/remoting2/clients/UserAgents.java), but should be fine. I updated some of our usage of this class to use the default/fallback user strings.
  - `JaxRsClient` - most of the [diff](https://github.com/palantir/http-remoting/commits/develop/jaxrs-clients/src/main/java/com/palantir/remoting2/jaxrs/JaxRsClient.java) is infra to enable live reloading uris
- Server / Jersey stuff
  - `WebPreconditions` - is [identical](https://github.com/palantir/http-remoting/commits/develop/jersey-servers/src/main/java/com/palantir/remoting2/servers/jersey/WebPreconditions.java) across versions
  - `RemoteException` - is [identical](https://github.com/palantir/http-remoting/commits/develop/error-handling/src/main/java/com/palantir/remoting2/errors/RemoteException.java) across versions
  - `HttpRemotingJerseyFeature ` - most of the [diff](https://github.com/palantir/http-remoting/commits/develop/jersey-servers/src/main/java/com/palantir/remoting2/servers/jersey/HttpRemotingJerseyFeature.java) is adding cbor support

**Where should we start reviewing?**:
I guess look at the commits individually, starting with the first.

**Priority (whenever / two weeks / yesterday)**: Today / Tomorrow

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1999)

### CODE REVIEW

**Comment by tpetracca** [comment]
Worth noting that the actual diff here is `+101 −104`. Most of the number quoted in the PR info is because of the `version.lock` stuff.

**Comment by tpetracca** [comment]
Looks like I'm having some guava Optional vs. java Optional issues. Will try and see if I can fix in a minimal way instead of having to change the whole repo....

**Comment by tpetracca** [comment]
Just couldn't deserialize the java optional without the jdk8module. Separately I've filed #2001.

This should be good to go for review.

**Comment by nziebart** [comment]
cool, looks like this was a pretty straightforward change. the only actual code change i see is adding a `Jdk8Module` to the object mapper.

as a next step here, should/can we run the autobump on this branch?

**Comment by tpetracca** [comment]
Cool. So I just rebased on develop, fixed conflicts, and pushed. I don't particularly know how to do the autobump thing you're suggesting; could one of you kick it off?

**Comment by jeremyk-91** [comment]
@tpetracca no worries, I'll look into this.

**Comment by jeremyk-91** [comment]
Apparently develop is broken, so unfortunately it's going to be difficult to get signal from bumping. I'll continue to track this, but I think we need to fix that first.

**Comment by tpetracca** [comment]
Just fix the merge conflicts. Any other blockers here? It sounded like the develop fix happened yesterday to be able to run the autobump stuff. I'd like to see this get in before #2006.

**Comment by jeremyk-91** [comment]
@tpetracca I'm going to rebase this on develop, and then run said tests. We'd like to get this in before #2006, as noted.

**Comment by jeremyk-91** [comment]
Internal discussion: I'm going to resolve the merge conflicts, merge, and then run the autobumps. We safely released 0.44.0 and as far as I know the autobumps are in a good state now.

**Comment by tpetracca** [comment]
@jeremyk-91 something I realized is that I moved everything to remoting2, but didn't actually bump the version of remoting2. If we're seeing issues with autobumps after merging this theres a chance it's related to us now causing conflicting versions of remoting2 things downstream. We should consider bumping from `2.3.0` to `2.5.1` (or even one of the `2.6.0` rcs).

**Comment by uschi2000** [comment]
Think I can make a 2.6 .

**Pull request merged**
