### PR TITLE
allowed '_' and '-' in namespaces that are not namespace mapped

### PR DESCRIPTION
**Pull request by rjullman**

### CODE REVIEW

**Comment by markelliot** [comment]
What do you mean "not namespace mapped"?

**Comment by markelliot** [comment]
I don't think this change is correct.

The non-Gotham path (see `TransactionManagers`) invokes:

    NamespacedKeyValueServices.wrapWithStaticNamespaceMappingKvs(KeyValueService)

Which under the covers calls a stack of

    StaticTableMappingService.create(KeyValueService);
    TableRemappingKeyValueService.create(KeyValueService, TableMappingService);
    NamespaceMappingKeyValueService.create(NamespacedKeyValueService)

I think Gotham needs `KVTableMappingService` to allow the extra chars, and that the current block in `Namespace` still needs to essentially deny these characters.

**Comment by rjullman** [comment]
My understanding is that we only need to disallow _ and - when we use obfuscate namespace (because we use these characters as delimiters).  As such, it seems like correct behavior to not have the StaticTableMappingService do the more stringent test, but have the KVTableMappingService do the test instead.  Including the check in Namespaces (for all namespaces) is overly restrictive in that it doesn't allow uses to use delimiters (for their own organizational purposes) even when just doing static table mapping.

**Comment by markelliot** [comment]
I don't think the CassandraKeyValueService character correction fixes the use of hyphens (only use of periods), so this will allow characters that the data layer may then later reject.

**Comment by rjullman** [comment]
https://github.com/palantir/atlasdb/pull/104 is sufficient for my needs

**Pull request closed without merging**
