### PR TITLE
timestamp-impl does not export jmock and junit as compile dependency

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
@rjullman

**Comment by rjullman** [comment]
This is good with me, but it is going to conflict with https://github.com/palantir/atlasdb/pull/151 (pulls in internal updates and changes dependencies around).  Let's merge this after that.

**Comment by clockfort** [comment]
Fixed in https://github.com/palantir/atlasdb/pull/229 ; there seems to not be a great way to do the workflow for this.
I can't update this pull because it comes from uschi's own fork that I have no permissions on, and I can't do the merge and push it manually to develop because it yells at me for trying to bypass the on-commit tests.

Oh well.

**Comment by uschi2000** [comment]
cheers Chris

**Pull request closed without merging**
