### PR TITLE
Add methods to catch additional lock and unlock methods in the LockRe…

### PR DESCRIPTION
**Pull request by cholve**
Make sure to continually refresh all locks.

Backport of PR #1134 for the internal product.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1626)

### CODE REVIEW

**Comment by amrasarfeiniel** [comment]
+2 assuming you can get the build to pass

**Comment by cholve** [comment]
Hey @amrasarfeiniel,

It looks like the link to the build is dead... Also other PRs that have merged on the 0.4.x branch have been failing as well.  Is the internal build relevant here?

**Comment by cholve** [comment]
nvm DavidS got me the link to the build.  Looks like it's failing to load the cassandra docker image.  Looking into it now.

**Comment by cholve** [comment]
Soo.... doesn't look like the internal build has ever succeeded on the 0.4.x branch.  Thoughts on how to proceed here given that it doesn't look like the build is failing due to code changes?

**Comment by amrasarfeiniel** [comment]
probably have to wait for OSS atlas folks who own this project to shove it through for you.  I don't have owner on this thing.

**Comment by jboreiko** [comment]
Backport looks good.  @rjullman we appreciate the heads up and understand the velocity concerns here.  Cheers

**Pull request merged**
