### PR TITLE
Expose embedded lock and timestamp services

### PR DESCRIPTION
**Pull request by SerialVelocity**
---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/708)

### CODE REVIEW

**Comment by tpetracca** [comment]
Should we also do this if size of leaders is 1?

**Comment by schlosna** [comment]
If we have leader block with leaders of size 1, we probably still want it going through the if condition to wrap the individual leader in awaiting leadership proxy for lock & timestamp, that way online CLIs can hit the single leader.

**Comment by tpetracca** [comment]
It'll be able to hit it anyway (that's the whole point of this PR)

**Comment by jboreiko** [comment]
A few things I would like to see before we merge this
- [ ] a portion of this PR should be a table of supported / unsupported configurations
- [ ] for each of the above configurations we should have an ete test that starts up the stack in the given configuration

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java, line 218 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/708#-KNHUXJ4kN_yy7xNTTrG:-KNHUXJ4kN_yy7xNTTrH:-972141742) ([raw file](https://github.com/palantir/atlasdb/blob/1e87bc8accfad943eaedec5cc4347512e16bc2dc/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L218)):*
> ```Java
>                     .build();
>         } else {
>             warnIf(config.lock().isPresent() != config.timestamp().isPresent(), "Using embedded instances for one (but not both) of lock and timestamp services");
> ```

Should we allow this at all?  I can't think of a case were this would be the correct configuration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/708#-:-KNHSzGE8Tdg-lpUZRyB:-204201354)*

**Comment by SerialVelocity** [comment]
@schlosna @tpetracca I think they should be wrapped in the awaiting leadership proxy since we probably want to remove the embedded code path (we just make people have a leader block of size 1).

**Comment by joelea** [comment]
Entirely agree with @jboreiko 's comments - can we get those in soon and get this merged?

**Comment by tpetracca** [comment]
I started to write up docs / supported ocnfigs last week.  Will add in sometime tonight.

**Comment by joelea** [comment]
Ok, then @SerialVelocity we just want the test.

**Comment by gsheasby** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java, line 218 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/708#-KNHUXJ4kN_yy7xNTTrG:-KNgd_QTCgUTQrd_ECSf:-285080219) ([raw file](https://github.com/palantir/atlasdb/blob/1e87bc8accfad943eaedec5cc4347512e16bc2dc/atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java#L218)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Should we allow this at all?  I can't think of a case were this would be the correct configuration.
</details>
We should consider this, but outside the scope of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/708)*

**Pull request merged**
