### PR TITLE
Bump guava to 20.0, use getHost() instead of getHostText()

### PR DESCRIPTION
**Pull request by dansanduleac**
**Goals (and why)**:

So atlasdb can be used together with guava 22.0+.

Guava 20.0 deprecates `HostAndPort.getHostText()` and adds a replacement - `getHost()`, while guava 22.0 removes `getHostText()` ([deprecation PR](https://github.com/google/guava/commit/b0babb69b05ed4d15cce74635ae96cf8ba78c85f)).
Atlasdb is currently on 18.0, therefore it's necessary to bump to 20.0 so we can use the alternative method.

Please see the same change in http-remoting: https://github.com/palantir/http-remoting/pull/655

**Implementation Description (bullets)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2817)

### CODE REVIEW

**Comment by fsamuel-bs** [comment]
The large internal product seems to be on Guava 20, so I think we're safe to upgrade here. @jeremyk-91 @tboam thoughts?

**Comment by tboam** [comment]
@jeremyk-91 to review whether this is going to play badly with internal products and their dependencies

**Comment by hsaraogi** [comment]
This blocks #2926, so picking up now.

**Comment by hsaraogi** [comment]
atlasdb-config still resolves to guava-0.18.0 though gradle does the right thing. We should invesigate this but added #2929 to unblock the Qos exceptions PR.


```
11:24 $ ./gradlew atlasdb-config:dependencyInsight --dependency guava --configuration compile
:atlasdb-config:dependencyInsight
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
com.fasterxml.jackson.datatype:jackson-datatype-guava:2.6.7 (selected by rule)
+--- com.palantir.remoting2:error-handling:2.3.0
|    \--- compile
+--- com.palantir.remoting2:jackson-support:2.3.0
|    \--- com.palantir.remoting2:error-handling:2.3.0 (*)
+--- com.palantir.remoting3:jackson-support:3.14.0
|    +--- com.palantir.remoting3:tracing:3.14.0
|    |    +--- compile
|    |    +--- project :atlasdb-impl-shared
|    |    |    \--- compile
|    |    +--- project :leader-election-impl
|    |    |    \--- compile
|    |    +--- project :lock-impl
|    |    |    +--- compile
|    |    |    \--- project :atlasdb-impl-shared (*)
|    |    +--- project :atlasdb-client
|    |    |    +--- project :atlasdb-impl-shared (*)
|    |    |    \--- project :qos-service-impl
|    |    |         \--- compile
|    |    +--- com.palantir.remoting3:jersey-servers:3.14.0
|    |    |    \--- project :atlasdb-impl-shared (*)
|    |    +--- project :commons-executors
|    |    |    \--- project :atlasdb-commons
|    |    |         +--- project :atlasdb-api
|    |    |         |    +--- compile
|    |    |         |    +--- project :atlasdb-lock-api
|    |    |         |    |    \--- project :atlasdb-impl-shared (*)
|    |    |         |    \--- project :atlasdb-client (*)
|    |    |         +--- project :atlasdb-impl-shared (*)
|    |    |         +--- project :leader-election-impl (*)
|    |    |         +--- project :lock-impl (*)
|    |    |         +--- project :timestamp-client
|    |    |         |    +--- compile
|    |    |         |    \--- project :atlasdb-impl-shared (*)
|    |    |         +--- project :lock-api
|    |    |         |    +--- project :atlasdb-feign
|    |    |         |    |    \--- compile
|    |    |         |    +--- project :lock-impl (*)
|    |    |         |    \--- project :atlasdb-lock-api (*)
|    |    |         +--- project :atlasdb-client (*)
|    |    |         \--- project :leader-election-api
|    |    |              \--- project :leader-election-impl (*)
|    |    \--- com.palantir.remoting3:tracing-okhttp3:3.14.0
|    |         +--- com.palantir.remoting3:jaxrs-clients:3.14.0
|    |         |    +--- project :atlasdb-api (*)
|    |         |    \--- project :qos-service-api
|    |         |         +--- project :atlasdb-api (*)
|    |         |         +--- project :atlasdb-impl-shared (*)
|    |         |         +--- project :qos-service-impl (*)
|    |         |         \--- project :atlasdb-client (*)
|    |         \--- com.palantir.remoting3:okhttp-clients:3.14.0
|    |              \--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
|    +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
|    \--- com.palantir.remoting3:error-handling:3.14.0
|         +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
|         +--- com.palantir.remoting3:jersey-servers:3.14.0 (*)
|         \--- com.palantir.remoting3:okhttp-clients:3.14.0 (*)
+--- com.palantir.remoting3:tracing:3.14.0 (*)
\--- io.dropwizard:dropwizard-jackson:0.9.3
     \--- compile

com.fasterxml.jackson.datatype:jackson-datatype-guava: -> 2.6.7
\--- project :atlasdb-client
     +--- project :atlasdb-impl-shared
     |    \--- compile
     \--- project :qos-service-impl
          \--- compile

com.google.guava:guava:20.0 (selected by rule)
+--- com.palantir.remoting3:error-handling:3.14.0
|    +--- com.palantir.remoting3:jaxrs-clients:3.14.0
|    |    +--- project :atlasdb-api
|    |    |    +--- compile
|    |    |    +--- project :atlasdb-lock-api
|    |    |    |    \--- project :atlasdb-impl-shared
|    |    |    |         \--- compile
|    |    |    \--- project :atlasdb-client
|    |    |         +--- project :atlasdb-impl-shared (*)
|    |    |         \--- project :qos-service-impl
|    |    |              \--- compile
|    |    \--- project :qos-service-api
|    |         +--- project :atlasdb-api (*)
|    |         +--- project :atlasdb-impl-shared (*)
|    |         +--- project :qos-service-impl (*)
|    |         \--- project :atlasdb-client (*)
|    +--- com.palantir.remoting3:jersey-servers:3.14.0
|    |    \--- project :atlasdb-impl-shared (*)
|    \--- com.palantir.remoting3:okhttp-clients:3.14.0
|         \--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
+--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
+--- com.palantir.remoting3:keystores:3.14.0
|    +--- compile
|    +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
|    \--- com.palantir.remoting3:http-clients:3.14.0
|         +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
|         \--- com.palantir.remoting3:okhttp-clients:3.14.0 (*)
+--- com.palantir.remoting3:okhttp-clients:3.14.0 (*)
+--- com.palantir.remoting3:refresh-utils:3.14.0
|    +--- project :atlasdb-feign
|    |    \--- compile
|    \--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
\--- com.palantir.remoting3:tracing:3.14.0
     +--- compile
     +--- project :atlasdb-impl-shared (*)
     +--- project :leader-election-impl
     |    \--- compile
     +--- project :lock-impl
     |    +--- compile
     |    \--- project :atlasdb-impl-shared (*)
     +--- project :atlasdb-client (*)
     +--- com.palantir.remoting3:jersey-servers:3.14.0 (*)
     +--- project :commons-executors
     |    \--- project :atlasdb-commons
     |         +--- project :atlasdb-api (*)
     |         +--- project :atlasdb-impl-shared (*)
     |         +--- project :leader-election-impl (*)
     |         +--- project :lock-impl (*)
     |         +--- project :timestamp-client
     |         |    +--- compile
     |         |    \--- project :atlasdb-impl-shared (*)
     |         +--- project :lock-api
     |         |    +--- project :atlasdb-feign (*)
     |         |    +--- project :lock-impl (*)
     |         |    \--- project :atlasdb-lock-api (*)
     |         +--- project :atlasdb-client (*)
     |         \--- project :leader-election-api
     |              \--- project :leader-election-impl (*)
     \--- com.palantir.remoting3:tracing-okhttp3:3.14.0
          +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
          \--- com.palantir.remoting3:okhttp-clients:3.14.0 (*)

com.google.guava:guava: -> 20.0
\--- project :atlasdb-commons
     +--- project :atlasdb-api
     |    +--- compile
     |    +--- project :atlasdb-lock-api
     |    |    \--- project :atlasdb-impl-shared
     |    |         \--- compile
     |    \--- project :atlasdb-client
     |         +--- project :atlasdb-impl-shared (*)
     |         \--- project :qos-service-impl
     |              \--- compile
     +--- project :atlasdb-impl-shared (*)
     +--- project :leader-election-impl
     |    \--- compile
     +--- project :lock-impl
     |    +--- compile
     |    \--- project :atlasdb-impl-shared (*)
     +--- project :timestamp-client
     |    +--- compile
     |    \--- project :atlasdb-impl-shared (*)
     +--- project :lock-api
     |    +--- project :atlasdb-feign
     |    |    \--- compile
     |    +--- project :lock-impl (*)
     |    \--- project :atlasdb-lock-api (*)
     +--- project :atlasdb-client (*)
     \--- project :leader-election-api
          \--- project :leader-election-impl (*)

com.google.guava:guava:15.0 -> 20.0
\--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.6.7
     +--- com.palantir.remoting2:error-handling:2.3.0
     |    \--- compile
     +--- com.palantir.remoting3:tracing:3.14.0
     |    +--- compile
     |    +--- project :atlasdb-impl-shared
     |    |    \--- compile
     |    +--- project :leader-election-impl
     |    |    \--- compile
     |    +--- project :lock-impl
     |    |    +--- compile
     |    |    \--- project :atlasdb-impl-shared (*)
     |    +--- project :atlasdb-client
     |    |    +--- project :atlasdb-impl-shared (*)
     |    |    \--- project :qos-service-impl
     |    |         \--- compile
     |    +--- com.palantir.remoting3:jersey-servers:3.14.0
     |    |    \--- project :atlasdb-impl-shared (*)
     |    +--- project :commons-executors
     |    |    \--- project :atlasdb-commons
     |    |         +--- project :atlasdb-api
     |    |         |    +--- compile
     |    |         |    +--- project :atlasdb-lock-api
     |    |         |    |    \--- project :atlasdb-impl-shared (*)
     |    |         |    \--- project :atlasdb-client (*)
     |    |         +--- project :atlasdb-impl-shared (*)
     |    |         +--- project :leader-election-impl (*)
     |    |         +--- project :lock-impl (*)
     |    |         +--- project :timestamp-client
     |    |         |    +--- compile
     |    |         |    \--- project :atlasdb-impl-shared (*)
     |    |         +--- project :lock-api
     |    |         |    +--- project :atlasdb-feign
     |    |         |    |    \--- compile
     |    |         |    +--- project :lock-impl (*)
     |    |         |    \--- project :atlasdb-lock-api (*)
     |    |         +--- project :atlasdb-client (*)
     |    |         \--- project :leader-election-api
     |    |              \--- project :leader-election-impl (*)
     |    \--- com.palantir.remoting3:tracing-okhttp3:3.14.0
     |         +--- com.palantir.remoting3:jaxrs-clients:3.14.0
     |         |    +--- project :atlasdb-api (*)
     |         |    \--- project :qos-service-api
     |         |         +--- project :atlasdb-api (*)
     |         |         +--- project :atlasdb-impl-shared (*)
     |         |         +--- project :qos-service-impl (*)
     |         |         \--- project :atlasdb-client (*)
     |         \--- com.palantir.remoting3:okhttp-clients:3.14.0
     |              \--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
     +--- io.dropwizard:dropwizard-jackson:0.9.3
     |    \--- compile
     +--- project :atlasdb-client (*)
     +--- com.palantir.remoting2:jackson-support:2.3.0
     |    \--- com.palantir.remoting2:error-handling:2.3.0 (*)
     \--- com.palantir.remoting3:jackson-support:3.14.0
          +--- com.palantir.remoting3:tracing:3.14.0 (*)
          +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
          \--- com.palantir.remoting3:error-handling:3.14.0
               +--- com.palantir.remoting3:jaxrs-clients:3.14.0 (*)
               +--- com.palantir.remoting3:jersey-servers:3.14.0 (*)
               \--- com.palantir.remoting3:okhttp-clients:3.14.0 (*)

com.google.guava:guava:18.0 -> 20.0
+--- com.palantir.common:streams:1.9.0
|    \--- project :atlasdb-impl-shared
|         \--- compile
+--- com.palantir.config.crypto:encrypted-config-value:1.0.0
|    \--- com.palantir.config.crypto:encrypted-config-value-module:1.0.0
|         \--- compile
+--- com.palantir.config.crypto:encrypted-config-value-module:1.0.0 (*)
+--- com.palantir.remoting2:error-handling:2.3.0
|    \--- compile
+--- com.palantir.tritium:tritium-core:0.9.0
|    +--- com.palantir.tritium:tritium-lib:0.9.0
|    |    +--- compile
|    |    \--- project :atlasdb-client
|    |         +--- project :atlasdb-impl-shared (*)
|    |         \--- project :qos-service-impl
|    |              \--- compile
|    +--- com.palantir.tritium:tritium-metrics:0.9.0
|    |    +--- com.palantir.tritium:tritium-lib:0.9.0 (*)
|    |    \--- project :atlasdb-client (*)
|    +--- com.palantir.tritium:tritium-slf4j:0.9.0
|    |    \--- com.palantir.tritium:tritium-lib:0.9.0 (*)
|    \--- com.palantir.tritium:tritium-tracing:0.9.0
|         \--- com.palantir.tritium:tritium-lib:0.9.0 (*)
+--- com.palantir.tritium:tritium-lib:0.9.0 (*)
+--- com.palantir.tritium:tritium-metrics:0.9.0 (*)
+--- io.dropwizard:dropwizard-jackson:0.9.3
|    \--- compile
\--- io.dropwizard:dropwizard-util:0.9.3
     \--- io.dropwizard:dropwizard-jackson:0.9.3 (*)
```

**Pull request merged**
