### PR TITLE
[TS] Part 11: Shards Config, Adding Background Threads, Refactors

### PR DESCRIPTION
**Pull request by gmaretic**
**Goals (and why)**:
Get Sweep Queue to a fully functional state.

**Implementation Description (bullets)**:
Shards are live reloadable and refreshed every 5 minutes by checking both the persisted value and the config. The daly is fine, since nothing can be omitted.
The number of threads is not live reloadable, and they should be cleaned up properly as the TM is closed.
Refactored the whole mess with persister, reader, etc and now there is one class to deal with that logic.

**Concerns (what feedback would you like?)**:
Is there a reason to make the number of threads live reloadable? Seems like it would be quite messy to implement without a compelling reason to have it.
I am not happy with the config bloat that is happening, but do not know how to deal with it -- is there something that can go? Is it reasonable to put the thread number configs into runtime even though it is not live reloaded actually?
Also, a lot of the interfaces that were previously there are now not implemented as it required too much jumping through hoops -- the original idea partitioned operations on table reference, but now we do it on shard and strategy which gets messy, again without a compelling reason (cleaner API but messier implementation is not really a good argument)

**Where should we start reviewing?**:
`KvsSweepQueue.java`

**Priority (whenever / two weeks / yesterday)**:
Still a bit rough around the edges, so even an incomplete review would be very helpful

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163)

### CODE REVIEW

**Comment by gsheasby** [comment]
Immediate thoughts on the concerns:
"Is there a reason to make the number of threads live reloadable? Seems like it would be quite messy to implement without a compelling reason to have it.
I am not happy with the config bloat that is happening, but do not know how to deal with it -- is there something that can go? Is it reasonable to put the thread number configs into runtime even though it is not live reloaded actually?"

It would be nice for the number of threads to live-reload, but mainly because it would be nice for everything to live-reload. But, I don't think "everything live reloadable" is even close to the roadmap for now, so not worth doing it for the sake of it.
It's not reasonable to put config into runtime when it isn't live reloaded. That will just confuse someone down the line when they have some urgent reason to update the config.

**Comment by gsheasby** [comment]
Reviewed 1 of 36 files at r1.
Review status: 1 of 36 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 37 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChoNxs2hVhCoBPNu5O:-LChoNxs2hVhCoBPNu5P:b-4hyed1) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L37)):*
> ```Java
> public class KvsSweepQueue implements MultiTableSweepQueueWriter {
>     private final Supplier<Boolean> runSweep;
>     private final Supplier<Integer> shardsConfig;
> ```

nit: I preferred the old name...

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 38 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChng2u31tSUpW5ZCRf:-LChng2v7aP4Ii96wvum:b-vlun42) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L38)):*
> ```Java
>     private final Supplier<Boolean> runSweep;
>     private final Supplier<Integer> shardsConfig;
>     int conservativeThreads;
> ```

Private? (intellij informs me that `tables` can be made private, too).

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 49 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChoc5NCb2Du4POB4hh:-LChoc5NCb2Du4POB4hi:bv1vmjc) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L49)):*
> ```Java
>     private ScheduledExecutorService thoroughScheduler;
>     private final AtomicLong conservativeCounter = new AtomicLong(0);
>     private final AtomicLong thoroughCounter = new AtomicLong(0);
> ```

There are numerous fields here with conservative and thorough counterparts. I wonder if this is the right place to make that distinction, or if they should be grouped in some way...

After inspection, looks like they're all only used in thread creation and shutdown, so you may want to extract a class that does the scheduling and shutdown.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 65 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChos7-4EhO64Ml89PA:-LChos7-4EhO64Ml89PB:b-gytajn) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L65)):*
> ```Java
> 
>     @VisibleForTesting
>     @Deprecated
> ```

Seems a bit weird to add a new thing as deprecated, but I guess you're making another attempt to make sure nobody does this.  Perhaps add a comment?

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 88 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChpI5620dNSgyBFzAr:-LChpI576a9VIPSED7Q3:bgtlkxd) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L88)):*
> ```Java
> 
>     private void createAndStartBackgroundThreads() {
>         if (conservativeThreads > 0) {
> ```

Nit: duplicated logic

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 108 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChqHSWDpZJ-XILQk5J:-LChqHSWDpZJ-XILQk5K:biof6iv) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L108)):*
> ```Java
>     }
> 
>     int getNextShard(AtomicLong counter) {
> ```

This is only used twice. Logically, it's only used once.

Private? Or inline once the duplication above is cleaned up.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 111 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChpcw6DBwWHgDhdi3z:-LChpcw6DBwWHgDhdi4-:bdd6uhg) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L111)):*
> ```Java
>         return tables.modShards(counter.getAndIncrement());
>     }
>     @Override
> ```

nit: missing blank line

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163)*

**Comment by gsheasby** [comment]
Reviewed 35 of 36 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java, line 39 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiBdVNAg0TGVoMYTWx:-LCiBdVNAg0TGVoMYTWy:bjwa7hh) ([raw file](https://github.com/palantir/atlasdb/blob/8f0d41c53f9b886c867315b8a0707e30862bf908/atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java#L39)):*
> ```Java
> import com.palantir.atlasdb.sweep.queue.test.InMemorySweepQueueProcessorFactory;
> 
> // todo(gmaretic): fix
> ```

:tada: 

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueProcessor.java, line 29 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiDmDM-eFSA9KWQQhR:-LCiDmDM-eFSA9KWQQhS:b-olo8sw) ([raw file](https://github.com/palantir/atlasdb/blob/8f0d41c53f9b886c867315b8a0707e30862bf908/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueProcessor.java#L29)):*
> ```Java
>     public SweepQueueProcessor(
>             Supplier<Long> sweepTimestamp,
>             SweepQueueReader reader,
> ```

SweepQueueReader is now an unused interface, and should be removed.

---

*[atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueueNumShardSupplierTest.java, line 106 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCi7wr685KUBvjTUgp5:-LCi7wr685KUBvjTUgp6:boypoim) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueueNumShardSupplierTest.java#L106)):*
> ```Java
> 
>     @Test
>     public void getBeforeRefreshTimeDoesNotCHeckConfigOrUpdateProgress() throws InterruptedException {
> ```

nit: `CHeck`

---

*[atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepQueueTablesTest.java, line 50 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiAjoYDshxEGspFTtn:-LCiAjoZ2-u3reDHWzDu:b5ae728) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepQueueTablesTest.java#L50)):*
> ```Java
>     static final long TS_FINE_PARTITION = tsPartitionFine(TS);
>     static final long TS2_FINE_PARTITION = tsPartitionFine(TS2);
>     static final int FIXED_SHARD = WriteInfo.write(TABLE_CONS, getCellWithFixedHash(0), 0L).toShard(128);
> ```

Magic number 128 here and below

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163)*

**Comment by gmaretic** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 37 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChoNxs2hVhCoBPNu5O:-LCizjmt15y7DGeWbb22:bxmi9v4) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L37)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

nit: I preferred the old name...
</blockquote></details>

The new name reflects the fact that this is just the runtime config for the number of shards, not necessarily the number of shards (which is the max of this and the persisted value)

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 49 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChoc5NCb2Du4POB4hh:-LCj6I5S1rBi-6PKVw8O:b-4c7jme) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L49)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

There are numerous fields here with conservative and thorough counterparts. I wonder if this is the right place to make that distinction, or if they should be grouped in some way...

After inspection, looks like they're all only used in thread creation and shutdown, so you may want to extract a class that does the scheduling and shutdown.
</blockquote></details>

Makes sense -- refactored into an inner class

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 65 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChos7-4EhO64Ml89PA:-LCmKrBYBKniCppCpid_:b86bs9u) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L65)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Seems a bit weird to add a new thing as deprecated, but I guess you're making another attempt to make sure nobody does this.  Perhaps add a comment?
</blockquote></details>

Realised this ended up being used in one place only, so i inlined it there

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 108 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChqHSWDpZJ-XILQk5J:-LCmLD3GCV4SJDS-AEZl:bfyvgyf) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L108)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

This is only used twice. Logically, it's only used once.

Private? Or inline once the duplication above is cleaned up.
</blockquote></details>

Didn't inline for readability, but refactored 

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163)*

**Comment by gmaretic** [comment]
Needed someone to point out the obvious :duck: 
Fixed the configuration mess :lgtm: 

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java, line 39 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiBdVNAg0TGVoMYTWx:-LCmMKDkCuSP6T5H1Ext:b5aqds2) ([raw file](https://github.com/palantir/atlasdb/blob/8f0d41c53f9b886c867315b8a0707e30862bf908/atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java#L39)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

:tada: 
</blockquote></details>

:medal_sports: 

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 38 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChng2u31tSUpW5ZCRf:-LCmMwF9CGI-9vv3y1x8:b-zgg00d) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L38)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Private? (intellij informs me that `tables` can be made private, too).
</blockquote></details>

Refactored it out

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 88 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChpI5620dNSgyBFzAr:-LCmMzjn1Ax8-Mv2lpxu:b-x9b4ca) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L88)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Nit: duplicated logic
</blockquote></details>

Refactored

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 111 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChpcw6DBwWHgDhdi3z:-LCmNPfEBKqKZMOz5UKU:b-8fx2u7) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L111)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

nit: missing blank line
</blockquote></details>

:+1: 

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueProcessor.java, line 29 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiDmDM-eFSA9KWQQhR:-LCmN3MY0Nc9G-fLF29X:bmeyrwp) ([raw file](https://github.com/palantir/atlasdb/blob/8f0d41c53f9b886c867315b8a0707e30862bf908/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueProcessor.java#L29)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

SweepQueueReader is now an unused interface, and should be removed.
</blockquote></details>

:+1: 

---

*[atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueueNumShardSupplierTest.java, line 106 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCi7wr685KUBvjTUgp5:-LCmO4JLBp3u29o9wyDu:b-896fix) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueueNumShardSupplierTest.java#L106)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

nit: `CHeck`
</blockquote></details>

Done.

---

*[atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepQueueTablesTest.java, line 50 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCiAjoYDshxEGspFTtn:-LCmNMjF4HjTgMe8n_km:begaqmz) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepQueueTablesTest.java#L50)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Magic number 128 here and below
</blockquote></details>

Extracted

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163#-:-LCmZUmw3WVkx5goNiSR:bua0cd)*

**Comment by gsheasby** [comment]
Almost there. All that remains now:
- Some confusion around naming (the constants, and the config class name)
- The defaults seem wrong
- One question about the config checking

---

Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java, line 131 at r2](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCn8t6p5VAfelKV_OjC:-LCn8t6p5VAfelKV_OjD:bmbtg6u) ([raw file](https://github.com/palantir/atlasdb/blob/bb368a7a8ca7ac498c354e48592c955ed3fdc5dc/atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java#L131)):*
> ```Java
> 
>     public static final boolean DEFAULT_ENABLE_SWEEP_QUEUE = false;
>     public static final boolean DEFAULT_ENABLE_TARGETED_SWEEP = true;
> ```

This is confusing - not sure what the difference between these two is...
Perhaps: `DEFAULT_ENABLE_SWEEP_QUEUE_WRITES` and `DEFAULT_ENABLE_TARGETED_SWEEP`.

The defaults also make no sense together according to the comment in TargetedSweepConfig.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java, line 73 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCnAXy9EgU9y8aUoiBK:-LCnAXy9EgU9y8aUoiBL:b-qdgsb3) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java#L73)):*
> ```Java
> 
>     @Value.Check
>     void checkThoroughThreads() {
> ```

We should probably still sanity check that the thread count is non-negative. Also what does it mean to have 0 threads? We never actually process (in this case) thorough tables? Also noting that we have to move away from the requirement that thread count <= shard count. Probably no big deal - if there are say 5 threads and 2 shards, then 3 threads just go unused.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java, line 28 at r2](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCn9kYn4f8PCRrt66pb:-LCn9kYn4f8PCRrt66pc:b-dgujux) ([raw file](https://github.com/palantir/atlasdb/blob/bb368a7a8ca7ac498c354e48592c955ed3fdc5dc/atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java#L28)):*
> ```Java
> @JsonSerialize(as = ImmutableTargetedSweepConfig.class)
> @Value.Immutable
> public class TargetedSweepConfig {
> ```

Consider calling this `TargetedSweepInstallConfig` for disambiguation - it wasn't clear to me that this was install config until I read the javadoc and then noticed `TargetedSweepRuntimeConfig`.

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 37 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChoNxs2hVhCoBPNu5O:-LCnCkhf76HV9A3PIvd3:b4td80k) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L37)):*
<details><summary><i>Previously, gmaretic wrote…</i></summary><blockquote>

The new name reflects the fact that this is just the runtime config for the number of shards, not necessarily the number of shards (which is the max of this and the persisted value)
</blockquote></details>

OK, makes sense. Nit withdrawn!

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 38 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChng2u31tSUpW5ZCRf:-LCnCpmf99BfiF32gm6Q:bjwa7hh) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L38)):*
<details><summary><i>Previously, gmaretic wrote…</i></summary><blockquote>

Refactored it out
</blockquote></details>

:tada: 

---

*[atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java, line 108 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LChqHSWDpZJ-XILQk5J:-LCnD7xK2kiTJibkn7Vi:b6cne70) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/KvsSweepQueue.java#L108)):*
<details><summary><i>Previously, gmaretic wrote…</i></summary><blockquote>

Didn't inline for readability, but refactored 
</blockquote></details>

OK, sounds good :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163#-:-LCnD_Co5QaZutdDQRdm:b-o4bnxq)*

**Comment by gmaretic** [comment]
Should be all good now! Thanks :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java, line 131 at r2](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCn8t6p5VAfelKV_OjC:-LCnWNXBA8b3dWK_vgIN:b-szxi90) ([raw file](https://github.com/palantir/atlasdb/blob/bb368a7a8ca7ac498c354e48592c955ed3fdc5dc/atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java#L131)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

This is confusing - not sure what the difference between these two is...
Perhaps: `DEFAULT_ENABLE_SWEEP_QUEUE_WRITES` and `DEFAULT_ENABLE_TARGETED_SWEEP`.

The defaults also make no sense together according to the comment in TargetedSweepConfig.
</blockquote></details>

The defaults assume that if you enable writes to the sweep queue, you also want to run targeted sweep. But if you don't want to write to the queue, then you cannot run targeted sweep, so the config is ignored. That said, this is counterintuitive, so I'm fine with defaulting both to false.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java, line 73 at r1](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCnAXy9EgU9y8aUoiBK:-LCnWpOW4h-fPkOrQd6N:b-p5zgkk) ([raw file](https://github.com/palantir/atlasdb/blob/890e47e98f592430aafe70f46b6b25195d133af1/atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java#L73)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

We should probably still sanity check that the thread count is non-negative. Also what does it mean to have 0 threads? We never actually process (in this case) thorough tables? Also noting that we have to move away from the requirement that thread count <= shard count. Probably no big deal - if there are say 5 threads and 2 shards, then 3 threads just go unused.
</blockquote></details>

I removed the check since we don't do it in other configs (e.g. getBackgroundScrubThreads). Nothing horrible will happen if we have more threads than shards, but some of the work may be duplicated as threads can end up doing the same sweep.
0 threads is a convenient way to not run one type of sweep (conservative or thorough), setting both to 0 just hard disables targeted sweep while still persisting the information to the queue for possible future use.
In any case, we could do >=0 && <= MAX_SHARDS, just to avoid sad times.

---

*[atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java, line 28 at r2](https://reviewable.io/reviews/palantir/atlasdb/3163#-LCn9kYn4f8PCRrt66pb:-LCnWBEL6ZqDlWWrrELN:b1ubcge) ([raw file](https://github.com/palantir/atlasdb/blob/bb368a7a8ca7ac498c354e48592c955ed3fdc5dc/atlasdb-config/src/main/java/com/palantir/atlasdb/config/TargetedSweepConfig.java#L28)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary><blockquote>

Consider calling this `TargetedSweepInstallConfig` for disambiguation - it wasn't clear to me that this was install config until I read the javadoc and then noticed `TargetedSweepRuntimeConfig`.
</blockquote></details>

Makes sense

---


*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163#-:-LCnb8wTB11JNFEcBe05:bd3f65c)*

**Comment by gsheasby** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3163#-:-LCnikFBB60-ypBLweV2:bnfp4nl)*

**Pull request merged**
