### PR TITLE
Initial release notes

### PR DESCRIPTION
**Pull request by joelea**
We could do to have a better process for release notes, this would give us a continuously updated copy of the release notes that anyone can easily copy and paste whenever they need to do a release.

@tpetracca @schlosna @rjullman @clockfort @tmgordeeva @nemines @gbrova @jboreiko: What does everyone think of this?

(CSS stolen shamefully from @CRogers)

### CODE REVIEW

**Comment by tpetracca** [comment]
I imagine there are going to be things that don't make sense to force a release notes for, but generally yes I'm on board with the sentiment.

**Comment by schlosna** [comment]
In general 👍  

When prepping release would be good check the diff (e.g. https://github.com/palantir/atlasdb/compare/0.3.36...develop ) or use something like https://github.com/skywinder/Github-Changelog-Generator . This becomes easier if we squash pre-merge and make sure folks have good commit messages.

**Comment by joelea** [comment]
@tpetracca yep, definitely agree that it doesn't make sense for some things (so we can't do things like commit hooks), and some things would need multiple entries.

@schlosna That library looks pretty cool - we discussed the idea of doing it based on PRs but it lacked some of the benefits of adding release notes as we go. A bunch of internal teams have also had great success with this model.

**Comment by schlosna** [comment]
Works for me

**Pull request merged**
