### PR TITLE
[RFC] Timelock refactor

### PR DESCRIPTION
**Pull request by tpetracca**
Broke this up into two commits.

The first is more additions to `timelock-agent`
- `TimeLockAgent` class is vaguely a replacement for `timelock-server`'s `TimeLockServer`. It takes in a consumer that will register resources, and then creates and registers all timelocks necessary resources using it
- TimeLockAgent is abstract and will have an impl for every "algorithm", thus at the moment there will only be a `PaxosAgent` but I haven't actually start this yet (that's where most of the code will be I think)
- TimeLockAlgorithmInstallConfiguration now specifies a method its subclasses will implement that returns you a `TimeLockAgent`. This was the easiest way to get the correct impl without doing weird instanceof / getClass type of stuff. 

The second commit is just how `TimeLockServerLauncher` would be refactored to use `TimeLockAgent` as is relatively straightforward.

Thoughts on the general structure here? I have also already created a witchcraft version of this internally that uses `TimeLockAgent` as well. It's a comically small amount of code, and like the 2nd commit here, is super straightforward.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2156)

### CODE REVIEW

**Comment by tpetracca** [comment]
I forgot I had that first commit in there which was leftover on my branch from #2152; ignore that

**Comment by nziebart** [comment]
I'm out today but just read over the description. Why don't we just get rid of the algorithm interface and make everything paxos? I don't think anyone uses or will use atomix. Would that make things easier @tpetracca?

**Comment by jeremyk-91** [comment]
@tpetracca I think the general approach we have here looks solid. Following some of the offline discussions we've had, I'm going to start working on the `PaxosAgent` you mention if that's okay!

**Comment by jeremyk-91** [comment]
(also note that this isn't for develop, so some things like CI complaining are fine for this PR - they will be addressed in #2168 and/or the PR that is a request to merge the feature branch in to develop)

**Comment by jeremyk-91** [comment]
Merging to the feature branch for now.

**Pull request merged**
