### PR TITLE
Fix/ckvs extract table creation logic

### PR DESCRIPTION
**Pull request by gsheasby**
Refactoring PR.

Extracted two classes from CassandraKeyValueService(s):
* ColumnFamilyDefinition - deals with making a CfDef, and also checking if existing CfDefs match
* CassandraDao - for interfacing directly with Cassandra. So far, just has methods that rely on `describe_keyspace`, but can be added to during future refactors.

Net 96 lines removed from CassandraKVS.

A step towards being able to test CKVS.filterOutExistingTables, which could go in its own method, although it does something odd with carrying metadata around, so I'm not yet sure what to do.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/1070)

### CODE REVIEW

**Comment by jboreiko** [comment]
Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDao.java, line 31 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMdxMywve3kUdzfuhc:-KUMdxMywve3kUdzfuhd:bo3mp38) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDao.java#L31)):*
> ```Java
> import com.palantir.common.base.Throwables;
> 
> class CassandraDao {
> ```

As discussed maybe change this to CassandraRawTables? and the functions to something like getExisting().  Might also be valuable to include the fact that it's unfiltered but maybe raw brings that connotation.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 1496 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMfjgtUa5ZxD7evh9j:-KUMfjgtUa5ZxD7evh9k:b-70eijp) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1496)):*
> ```Java
> 
>         // we don't even have a metadata table yet. Return empty map.
>         if (!cassandraDao.getExistingTables().contains(AtlasDbConstants.METADATA_TABLE)) {
> ```

There is a slight functionality change here since getExistingTables() doesn't map from internal table name.  In this case it's fine but it appears like we may want to just have a method that does the mapping since all of these uses do that mapping.  We can easily make the mapping method static in AbstractKeyValueService

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 34 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMb190TnY7M42UrMTg:-KUMb190TnY7M42UrMTh:b-r7ads6) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L34)):*
> ```Java
> 
> final class ColumnFamilyDefinitions {
>     private static Logger log = LoggerFactory.getLogger(ColumnFamilyDefinitions.class);
> ```

The logger this used to run from is CassandraKeyValueService.class and there is a comment next to it that says "// did this on purpose" which leads me to believe we should use the same logger and not adopt this new one.  I imagine this could break some log parsing code?

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 36 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMbz0TS3fvGCinx-pR:-KUMbz0TS3fvGCinx-pS:b-lix4w0) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L36)):*
> ```Java
>     private static Logger log = LoggerFactory.getLogger(ColumnFamilyDefinitions.class);
> 
>     private ColumnFamilyDefinitions() {
> ```

Seems like this class should also include CassandraConstants#getStandardCfDef since that definition is interdependent with the methods here

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 149 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMaqMLj_2EZsq0ri1e:-KUMaqMLj_2EZsq0ri1f:b-b0kmv4) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L149)):*
> ```Java
>         if (!Objects.equal(clientSide.compaction_strategy, clusterSide.compaction_strategy)) {
>             // consider equal "com.whatever.LevelledCompactionStrategy" and "LevelledCompactionStrategy"
>             if (clientSide.compaction_strategy != null
> ```

Possibly outside the scope of this refactor but this looks like a very testable boolean statement that has gotten us into trouble in the past

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1070)*

**Comment by gsheasby** [comment]
Review status: 3 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 1496 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMfjgtUa5ZxD7evh9j:-KURAKORYJvxlsHbAhES:b-e1vvlg) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1496)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> There is a slight functionality change here since getExistingTables() doesn't map from internal table name.  In this case it's fine but it appears like we may want to just have a method that does the mapping since all of these uses do that mapping.  We can easily make the mapping method static in AbstractKeyValueService
</details>
Ah yes, this used to be included in CassandraDao, but that required exposing fromInternalTableName. The change was partially undone, but this detail was lost. I have now added it back.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 34 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMb190TnY7M42UrMTg:-KURAfcEcQYRmHxzh_BM:bt2vr1b) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L34)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> The logger this used to run from is CassandraKeyValueService.class and there is a comment next to it that says "// did this on purpose" which leads me to believe we should use the same logger and not adopt this new one.  I imagine this could break some log parsing code?
</details>
Fixed.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 36 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMbz0TS3fvGCinx-pR:-KURB7Msf_XZ1E9-RC95:b-w6xyys) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L36)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Seems like this class should also include CassandraConstants#getStandardCfDef since that definition is interdependent with the methods here
</details>
Done. This exposes a rather tricky duplication between `getCfDef` and `getStandardCfDef`, which I will not attempt to fix in this PR.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 149 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMaqMLj_2EZsq0ri1e:-KURAhdUgrF2vH23yss2:b-wl8r0z) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L149)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> Possibly outside the scope of this refactor but this looks like a very testable boolean statement that has gotten us into trouble in the past
</details>
There are tests for it already, but only an integration test in `CassandraKeyValueServiceIntegrationTest`. I've added a simple test for the compaction strategy checker.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDao.java, line 31 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMdxMywve3kUdzfuhc:-KUR8zxrktaIr5cwD3tb:bmv0bfg) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDao.java#L31)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> As discussed maybe change this to CassandraRawTables? and the functions to something like getExisting().  Might also be valuable to include the fact that it's unfiltered but maybe raw brings that connotation.
</details>
I believe CassandraTables to be better (I don't think "raw" adds much).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1070)*

**Comment by gsheasby** [comment]
Some tests around metadata are failing; I'm looking into it.

**Comment by jboreiko** [comment]
Reviewed 3 of 7 files at r3, 4 of 5 files at r4.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java, line 36 at r2](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KUMbz0TS3fvGCinx-pR:-KUre-bh2LEMIikaot2y:bdbqbh6) ([raw file](https://github.com/palantir/atlasdb/blob/45c5d76e5721e69b557a6ce2bb0711da9d2b53ec/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java#L36)):*
<details><summary><i>Previously, gsheasby (Glenn Sheasby) wrote…</i></summary>
> Done. This exposes a rather tricky duplication between `getCfDef` and `getStandardCfDef`, which I will not attempt to fix in this PR.
</details>
Javadoc?  Seems like it would be good to differentiate between the two.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1070)*

**Comment by gsheasby** [comment]
@jboreiko good to merge?

**Comment by jboreiko** [comment]
:lgtm: just one little nit, merge away

---

Reviewed 1 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 1530 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KV0DP3i-22O2Onl7DOH:-KV0DP3i-22O2Onl7DOI:b-7jh76j) ([raw file](https://github.com/palantir/atlasdb/blob/02ad0666783fd348cf3c3f1c565d3c9550ed2672/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1530)):*
> ```Java
>     }
> 
>     private Stream<TableReference> getTableReferencesWithoutFiltering() {
> ```

nit: seems like these should be overloaded, the naming difference makes me think they have different functionality

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-:-KV0DglPTbMDbsfgMQ96:bsf6yhk)*

**Comment by gsheasby** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java, line 1530 at r5](https://reviewable.io:443/reviews/palantir/atlasdb/1070#-KV0DP3i-22O2Onl7DOH:-KV0FnO4ULsINglvMd6K:b57zctq) ([raw file](https://github.com/palantir/atlasdb/blob/02ad0666783fd348cf3c3f1c565d3c9550ed2672/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java#L1530)):*
<details><summary><i>Previously, jboreiko (John Boreiko) wrote…</i></summary>
> nit: seems like these should be overloaded, the naming difference makes me think they have different functionality
</details>
I tried to do that - the compiler complains, I think because the return types are too similar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/1070)*

**Pull request merged**
