### PR TITLE
move atlas dagger instantiation into its own project

### PR DESCRIPTION
**Pull request by rjullman**
This moves the dagger instantiation of atlas from the atlas cli project to a new project atlas-core so that we can share modular dagger instantiation of atlas.  To make this commit simple this does not change to make TransactionManagers.create actually use this dagger component.  In the future we may need an atlas-core-tests project to hold common dagger test configurations, but for now that is overkill.  Also, I'm happy to chuck this into an existing project if applicable -- the closest I found is atlasdb-api, which doesn't feel right.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/816)

### CODE REVIEW

**Comment by SerialVelocity** [comment]
Snippet from chat:
 - I would say rename atlasdb-core to atlasdb-dagger for now (so we can try and not make people pull in dagger stuff if they don't want to)
 - If it is necessary for them to pull it in, we can do something about it later.
 - But maybe we should see what it will be like after atlasdb-server

Open question to consider for future PRs:
  - Will dagger allow us to use the jsr330 @Scope-type tags so we don't add a dependency in every project on dagger?

**Comment by SerialVelocity** [comment]
Reviewed 38 of 39 files at r1.
Review status: 29 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

*[atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestAtlasDbServices.java, line 24 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/816#-KPs5vgunEuC60VMzoDg:-KPs5vgunEuC60VMzoDh:b3w0gtc) ([raw file](https://github.com/palantir/atlasdb/blob/ec528ef197e7d5592c65c160326ba07e5156acce/atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestAtlasDbServices.java#L24)):*
> ```Java
> import com.palantir.atlasdb.services.LockAndTimestampModule;
> import com.palantir.atlasdb.services.RawKeyValueServiceModule;
> import com.palantir.atlasdb.services.ServicesConfigModule;
> ```

Should we move this out of atlasdb-cli? It seems to be testing the dagger stuff.

---

*[atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestTransactionManagerModule.java, line 30 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/816#-KPs67Rlf1nYPsBYq9Bv:-KPs67Rlf1nYPsBYq9Bw:b-xa2vyz) ([raw file](https://github.com/palantir/atlasdb/blob/ec528ef197e7d5592c65c160326ba07e5156acce/atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestTransactionManagerModule.java#L30)):*
> ```Java
> import com.palantir.atlasdb.factory.TransactionManagers;
> import com.palantir.atlasdb.keyvalue.api.KeyValueService;
> import com.palantir.atlasdb.services.ServicesConfig;
> ```

This also shouldn't be cli either, right?

---

*[atlasdb-core/src/test/test.sh, line 1 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/816#-KPs6VipHITT5uDIpzl-:-KPs6VipHITT5uDIpzl0:bb76hiy) ([raw file](https://github.com/palantir/atlasdb/blob/ec528ef197e7d5592c65c160326ba07e5156acce/atlasdb-core/src/test/test.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

Wat?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/816)*

**Comment by SerialVelocity** [comment]
Reviewed 1 of 39 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/816)*

**Comment by SerialVelocity** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestAtlasDbServices.java, line 24 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/816#-KPs5vgunEuC60VMzoDg:-KPs80Dnp8AKF2OR8Ug6:bpz6ldk) ([raw file](https://github.com/palantir/atlasdb/blob/ec528ef197e7d5592c65c160326ba07e5156acce/atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestAtlasDbServices.java#L24)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> Should we move this out of atlasdb-cli? It seems to be testing the dagger stuff.
</details>
Ignore :)

---

*[atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestTransactionManagerModule.java, line 30 \[r1\]](https://reviewable.io:443/reviews/palantir/atlasdb/816#-KPs67Rlf1nYPsBYq9Bv:-KPs83C9QGVrwLlIS3th:bpz6ldk) ([raw file](https://github.com/palantir/atlasdb/blob/ec528ef197e7d5592c65c160326ba07e5156acce/atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/services/TestTransactionManagerModule.java#L30)):*
<details><summary><i>Previously, SerialVelocity (Ben Grabham) wrote…</i></summary>
> This also shouldn't be cli either, right?
</details>
Ignore :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/atlasdb/816)*

**Comment by rjullman** [comment]
> Will dagger allow us to use the jsr330 @Scope-type tags so we don't add a dependency in every project on dagger?

Dagger does use the standard @Scope tags and the other shared injection tags.  I think the issue is that the jsr330 spec requires injection annotations to be runtime is that other people can inspect that (http://stackoverflow.com/questions/36331169/why-scope-annotations-have-runtime-retention-in-dagger-2).  I may have misunderstood something, but basically dagger requires the annotations at runtime in order to meet the spec even though it doesn't actually use them (the dagger source contains the comment on the annotation runtime lines "// Allows runtimes to have specialized behavior interoperating with Dagger.")

**Pull request merged**
