### PR TITLE
Issue 2559 - AtlasConsole getRange can OOM

### PR DESCRIPTION
**Pull request by stefank-palantir**
**Goals (and why)**:

This PR is a speculative fix to https://github.com/palantir/atlasdb/issues/2559 – table(xyz).getRange() can OOM AtlasConsole.

I have a theory that this is issue is caused because the default batch size of queries
is 2000, which feels a little wide. It's also unfortunate that the batch size isn't configurable.

This commit brings that default down to 100, and adds a configurable batch size
for when we want to trade memory for performance. In future the user can simply pass `batch_size` into the range map.

**Implementation Description (bullets)**:

* Table.getRange actually already passes all the range parameters through to atlas.
* batch_size is a parameter that Atlas will expect and handle.
* However the existing Table.getRange code will convert all range parameters to lists, because `start` and `end` need to be lists but AtlasConsole allows the user to give a singleton.
* This doesn't make sense for `batch_size` – so if the user provides it, atlas console will crash because Atlas doesn't want a list.
* I've added a list of parameters which `Table.getRange` _should_ uplift to lists. The rest will be passed unaltered.
* I've also modified `Table.getRange` to pass a default batch size of 100, which feel safer.

**Testing (What was existing testing like?  What have you done to improve it?)**:

*** I haven't tested this at all. I would really appreciate a conversation around how best to test this, either in code or on a test rig. :) ***

**Concerns (what feedback would you like?)**:

Primarily testing, or maybe alternative methods for providing a batch size if folks have better suggestions.

**Where should we start reviewing?**:

It's a one-class change

**Priority (whenever / two weeks / yesterday)**:

At your convenience.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/3502)

### CODE REVIEW

**Comment by stefank-palantir** [comment]
*Let's not merge yet* – per the initial PR comment I haven't done any testing. I just wanted to get some code up for discussion.

I'll follow up with you guys out of band about what sensible ways to test this look like – I'm not sure how you would usually go about manual testing so would welcome some pointers :)

**Comment by sandorw** [comment]
@stefank-palantir what's the status of the testing you were going to do?

**Comment by stefank-palantir** [comment]
Still on me, sorry. Hoping to get to it in the next couple of weeks.

**Comment by sandorw** [comment]
Closing since this hasn't gotten any further response

**Pull request closed without merging**
