### PR TITLE
Feature/getrows benchmarks

### PR DESCRIPTION
**Pull request by gmaretic**
**Goals (and why)**:
Benchmark for KVS `getRows`, to capture the perf improvement by #1764

**Implementation Description (bullets)**:
We reuse the already existing CleanNarrowTable that has 10k rows. 

**Concerns (what feedback would you like?)**:
No concerns, but open to feedback.

**Where should we start reviewing?**:
KvsGetRowsBenchmarks.java

**Priority (whenever / two weeks / yesterday)**:
ASAP, as merging of #1764 is blocking on this.

### CODE REVIEW

**Comment by jnelson15** [comment]
Do the benchmarks run against a single-node Cassandra cluster? If not is there a way to guarantee we're running > 5k (batch size per host) against at least one of them?

**Comment by gmaretic** [comment]
@jnelson15 They do in fact run on a single node cluster!

**Comment by jnelson15** [comment]
Awesome. Looks good to me then

**Comment by gmaretic** [comment]
Did a verification run of all benchmarks to make sure nothing is breaking, so merging this in.

**Pull request merged**
