### PR TITLE
Make FLS use AutoDelegate

### PR DESCRIPTION
**Pull request by fsamuel-bs**
**Goals (and why)**: We had a P0 because we thought the FLS just forwarded the LockService methods. So we make it use AutoDelegate, to make more clear which methods are actually different.

What should the name of FLS be? Simplifying Lock Service? Optimizing Lock service?

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/atlasdb/2729)

### CODE REVIEW

**Comment by fsamuel-bs** [comment]
This fixes #2382.

**Comment by fsamuel-bs** [comment]
@dxiao for SA, as this will break the internal large product when we merge if we change the name of the FLS.

**Comment by fsamuel-bs** [comment]
Changed ForwardingLockService to SimplifyingLockService. @jeremyk-91 what do you think?

**Comment by gmaretic** [comment]
This is a breaking change now, so should add it to release notes

**Pull request merged**
